### ISSUE TITLE
请问会开源dockerfile么？或者给出手工搭建环境的流程么？

### ISSUE THREAD

**Issue by zdaiot** [IEIT-Yuan/Yuan-2.0#10]

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem

**Comment by zhaoxudong01** [comment]
> _No description provided._

会尽快开源dockerfile，目前开源的镜像是基于nvcr.io/nvidia/pytorch:23.05-py3搭建的，感谢支持

**Comment by zhaoxudong01** [comment]
可以通过docker pull yuanmodel/yuan2.0:V1-base，获得我们提供的镜像
