### ISSUE TITLE
关于模型训练、调参相关的几个基础问题

### ISSUE THREAD

**Issue by fredfany** [IEIT-Yuan/Yuan-2.0#100]
1、 模型的Huging Face版本与原始版本的区别，推荐优先使用哪个模型

2、数据调参的过程的数据集是否需要自己手动构造，如果有了原始数据，是否有相关的工具来自动生成数据集。举例来说，手头有一份关于“科研奖励制度”的word文件《XX学校科研奖励制度》，其内容大致如下，
XX学校科研奖励制度
总则：XXX
条款一：xxxxxxxxx
条款二：yyyyyyyy
条款N：
备注：
比如对于Huging Face 2.1B模型，是否有专门的工具来生成形如下面这样的数据文件，还是必须自己根据需要手动构造
  {
    "instruction": "你能为我推荐几部赛博朋克题材的电影吗？",
    "input": "",
    "output": "最经典的类型就是银翼杀手Blade Runner"
    ]
  },

3）有没有稍微详细的关于调参方面的指导，比如现在有3000条数据，是应该一次全部投入训练，还是分批分成多个轮次训练，如果多次训练学习率是否需要调整等

感谢！

**Comment by zhaoxudong01** [comment]
1. hf版本的模型与原始版本的模型是相同，优先使用哪个模型主要看使用习惯
2. 微调数据集需要自己手动构造
3. 模型调参，3000条数据可以构成数据集一次全部投入训练，不清楚您说的分批多轮训练的目的是什么。我们提供了不同规模模型的微调脚本，可以作为参考的超参数。

**Comment by fredfany** [comment]
> 微调数据集需要自己手动构造

--也就是说给到模型的必须是符合格式要求的样例，原始文件（word/execl）等必须自己负责转换

> 模型调参，3000条数据可以构成数据集一次全部投入训练，不清楚您说的分批多轮训练的目的是什么。我们提供了不同规模模型的微调脚本，可以作为参考的超参数

--这里的意思是，3000条数据，一次全部投入训练，与把3000条分成300条，分10次进行训练，从效果来说有没有区别

补充一个问题，我使用LLaMA模型对Yuan-2.0模型进行调参，使用2.1B的数据集，微调方法有：full、freeze、lora
假如我要调参的数据集有3000条左右，我应该用哪种方法（目前试过full和lora两种方法，好像lora的调参会把模型搞乱，full的方法稳妥一些，不清楚其中原理）

谢谢！

**Comment by zhaoxudong01** [comment]
1. 是的，必须自己转换，除非自己改写dataset类
2. 300是batch size还是数据集的大小。如果是数据集大小的话，分批次，每个批次训练多个epoch和一次性投入训练多个epoch是有区别的。
3. lora不会更新模型的原始参数，相关原理可以查阅lora的论文。

**Comment by fredfany** [comment]
非常感谢！另外补充几个问题：
1. 我的环境有8卡A800-SXM4-80GB，如果推理时指定8块卡，对于有些问题，发现共用到0~5共6块卡，每块使用率17%左右，但是有些问题的回答速度长达十几秒，而GPU并未用尽，这个是否正常

2. 对于有些难以回答的问题，模型好像始终在运算，但是没有返回。此时再提问之前能否回答的问题好像也响应不了。也就是说一旦提问了一个难题，模型好像就不能正常工作

3. 关于如何构造数据集，能让模型更智能一些，这方面有什么策略或建议，比如说,我构造了一条数据如下，经过数轮训练后，我向模型提问“请问西北XX科技大学现任校长是谁？”能得到正确的答案，但是当我问“你知道李天下是谁吗”，这时模型就开始乱答。甚至说当我提问“请问西北XX科技大学现任校长**是哪个人**”也得不到预期的答案。
这里面在构造数据时有哪些策略或技巧。

谢谢
```
  {
    "instruction": "请问西北XX科技大学现任校长是谁？",
    "input": "",
    "output": "李天下"
  },
```

**Comment by zhaoxudong01** [comment]
1. 是开启了8-way 张量并行是么？多大模型？推理过程中，GPU占用率会比较低。不会出现只使用6块卡的情况，显存占用可以看出来哪些卡被占用。
2. 是否生成的序列太长，可以尝试将生成的长度变短一点。
3. 是否训练次数过多导致过拟合？

**Comment by fredfany** [comment]
我用的是8卡A800-SXM4-80GB，模型为Yuan2.0 2.1B模型，
>是开启了8-way 张量并行是么？多大模型？推理过程中，GPU占用率会比较低。不会出现只使用6块卡的情况，显存占用可以看出来哪些卡被占用。

--推理脚本里指定CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7，推理过程中只看到0~5号卡在使用，7，8闲置
>是否生成的序列太长，可以尝试将生成的长度变短一点。

--这里说的序列是指数据集中的“output”字段吗，确实有点长，有些长度为500汉字甚至更长

>是否训练次数过多导致过拟合？

--训练了1000~2000个epoch，这个次数算多吗

**Comment by zhaoxudong01** [comment]
1. 2B模型部署在单卡上，推理过程只有一个卡在计算，其他卡是空闲状态。您监控到其他卡有被占用，可能有其他人也在使用。
2. 500 tokens，预计推理在20s左右，如果长时间没有返回，是不正常的，如果长时间没有响应，需要查看一下推理服务是否有报错。
3. 1000 epoch会存在过拟合，可以通过测试找到一个最优的epoch结果。

**Comment by fredfany** [comment]
![training_loss_ckp6_epoch_1000](https://github.com/IEIT-Yuan/Yuan-2.0/assets/36719270/4fba2994-f6a0-47b8-8680-addb628648e1)
这个图里的original应该表示实际loss值的变化吧，从这个来看在step为70左右的时候loss已经趋近于0了，一般来说应该把loss调到多大合适。

另外，如果loss已经降到一个合适的值，后续的训练是否就是多余的，或者说会产生副作用

**Comment by zhaoxudong01** [comment]
从loss曲线看是已经过拟合了。final loss与训练集的数据相关，过拟合对模型的通用性有副作用。

**Comment by fredfany** [comment]
在LLaMA框架下，使用自定义数据集微调Yuan2.0 2.1B模型，提示获得的样例(sample)数为0，微调过程失败，打印如下，找了很多解决办法都无效。
问一下：
1. 是否对这个问题有解决建议
2. 对于调参，LLaMA框架和原生框架megatron，怎么更推荐哪一个
谢谢

```
  Traceback (most recent call last):
  File "/workspace/LLaMA-Factory/src/train_bash.py", line 14, in <module>
    main()
  File "/workspace/LLaMA-Factory/src/train_bash.py", line 5, in main
    run_exp()
  File "/workspace/LLaMA-Factory/src/llmtuner/train/tuner.py", line 31, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/workspace/LLaMA-Factory/src/llmtuner/train/sft/workflow.py", line 75, in run_sft
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1553, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 800, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 770, in _get_train_sampler
    return RandomSampler(self.train_dataset)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 141, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by zhaoxudong01** [comment]
@wangpengfei1013

**Comment by wangpengfei1013** [comment]
> get_train_dataloader

数据集用的哪个？是否自己定义的呢？
将dataset改成这个试一试： --dataset alpaca_en

**Comment by fredfany** [comment]
使用--dataset custom, NWtest可以规避此问题，这两天数据集都是自定义的，第一个由alpaca_zh构造，语料条数较多，第二个只有少数几条。单独使用第二个有问题，联合使用可行。
感谢反馈，暂时关闭该问题，后续再观察。
