### ISSUE TITLE
如何在容器方式下，替换YuanChat服务的logo及头像文件

### ISSUE THREAD

**Issue by fredfany** [IEIT-Yuan/Yuan-2.0#106]
因为源码方式过程复杂，依赖太多，在容器方式下部署了YuanChat服务，参照源码方式替换YuanChat服务的logo及头像文件均未成功

1. 参考链接
[YuanChat](https://github.com/IEIT-Yuan/YuanChat/blob/main/README.md)

2. 容器内文件
```
root@7efc830bf589:/# ls -l /src/webui/public/
total 40
-rw-r--r-- 1 root root 22465 Jan  4 00:34 avatar-user.png
-rw-r--r-- 1 root root  1491 Jan  4 00:34 avatar-yuan.png
-rw-r--r-- 1 root root  2128 Jan  4 00:34 favicon.png
-rw-r--r-- 1 root root  2707 Jan  4 00:34 logo.png
-rw-r--r-- 1 root root  1691 Jan  4 00:34 recommends.json
root@7efc830bf589:/# ls -l /dist/
total 48
drwxr-xr-x 2 root root  4096 Jan  2 09:30 assets
-rw-r--r-- 1 root root 22465 Jan  2 09:30 avatar-user.png
-rw-r--r-- 1 root root  1491 Jan  2 09:30 avatar-yuan.png
-rw-r--r-- 1 root root  2128 Jan  2 09:30 favicon.png
-rw-r--r-- 1 root root   472 Jan  2 09:30 index.html
-rw-r--r-- 1 root root  2707 Jan  2 09:30 logo.png
-rw-r--r-- 1 root root  1691 Jan  2 09:30 recommends.json
root@7efc830bf589:/#
```

3. 替换方式
方式一：准备好自己的logo文件， 容器启动后，直接用docker cp命令拷贝覆盖logo.png、avatar-yuan.png，刷新页面无效
方式二：将自己的文件准备在custom目录下，容器启动时使用-v参数，映射容器的/dist或/src/webui/public目录，提示出错或无效
```
export YuanChatDist=/home/orcadt/workspace/YuanLLM/custom
#以下命令都试过，其结果是容器启动失败，页面报“Internal Server Error”
docker run --rm -d -v ${YuanChatDist}:/dist --name yuanchat -p 5050:5050 -e YUAN_2_URL=http://172.17.0.1:8000/yuan yuanmodel/yuanchat:latest /bin/sh
#以下命令未出错，但也未生效
docker run --rm -d -v ${YuanChatDist}:/src/webui/public --name yuanchat -p 5050:5050 -e YUAN_2_URL=http://172.17.0.1:8000/yuan yuanmodel/yuanchat:latest /bin/sh
```
4. 问题
是否有办法能在容器方式下替换自己的logo、头像文件等，谢谢

**Comment by wk-iei** [comment]
@fredfany  你好。容器环境下，logo.png、avatar-yuan.png保存在`/dist`目录下，可以执行  `docker cp avatar-yuan.png yuanchat:/dist/ `  `docker cp logo.png yuanchat:/dist`/ 两条命令后，清除浏览器缓存刷新页面看看。

**Comment by fredfany** [comment]
确实可以，这个方法一开始就试过，没有成功，应该是没有清楚浏览器缓存导致的，以为不必要，疏忽了。
非常感谢！

**Comment by fredfany** [comment]
麻烦再问一下，如果修改对话欢迎语，是否采用类似的方法（docker cp zh-CN.js container: /src/webui/src/locales/lang/zh-CN.js ），我拷贝完成之后刷写浏览器缓存重新访问，好像没有生效，谢谢
```
修改源 Chat 的对话欢迎语，需要修改 /src/webui/src/locales/lang/zh-CN.js 中的多语言配置，具体要修改以下内容：

  welcomeHeader: '我是源Chat，基于源2.0大模型的对话应用。',
  welcomeParagraph1: '我能够进行多轮对话，回答领域问题，协助人们进行应用文写作和艺术创作。',
```

**Comment by wk-iei** [comment]
> 麻烦再问一下，如果修改对话欢迎语，是否采用类似的方法（docker cp zh-CN.js container: /src/webui/src/locales/lang/zh-CN.js ），我拷贝完成之后刷写浏览器缓存重新访问，好像没有生效，谢谢
> 
> ```
> 修改源 Chat 的对话欢迎语，需要修改 /src/webui/src/locales/lang/zh-CN.js 中的多语言配置，具体要修改以下内容：
> 
>   welcomeHeader: '我是源Chat，基于源2.0大模型的对话应用。',
>   welcomeParagraph1: '我能够进行多轮对话，回答领域问题，协助人们进行应用文写作和艺术创作。',
> ```

容器方式部署暂不支持欢迎语修改

**Comment by fredfany** [comment]
好的，了解了

**Comment by wk-iei** [comment]
> 好的，了解了

可以尝试修改源码中的配置，重新编译静态文件获取dist目录，然后删除并替换容器中的`/dist`.
确保本地已安装Node.js ( >=18 )，编译获取静态文件，请参考以下命令。
```
cd YuanChat/src/webui
npm install
npm run build
```

**Comment by fredfany** [comment]
收到，感谢！
