### ISSUE TITLE
Is it serious to upload the mirror to Baidu Netdisk?

### ISSUE THREAD

**Issue by llanc** [IEIT-Yuan/Yuan-2.0#11]
Step 1 of using Yuan-2.0: Get a Baidu Netdisk SVIP to accelerate the download process!

**Comment by Shawn-IEITSystems** [comment]
Will upload the model files to open source community. Sorry!

**Comment by Shawn-IEITSystems** [comment]
Now Yuan2.0-2B is on modelscope. Link: https://www.modelscope.cn/models/YuanLLM/Yuan2.0-2B/files
51B and 102B is uploading.
