### ISSUE TITLE
与nvidia/megatron-lm的区别在哪里

### ISSUE THREAD

**Issue by zhouhang-chn** [IEIT-Yuan/Yuan-2.0#13]
没有基于megatron-lm 进行fork，看不到改动点

**Comment by Shawn-IEITSystems** [comment]
主要的改动在模型结构与分布式算法上，添加了LFA这种结构，添加了非均匀流水并行的实现。

**Comment by Shawn-IEITSystems** [comment]
@zhouhang-chn 请问对代码的改动是否还有疑问？欢迎更多的交流。如果没有后续的问题，我将关闭该issue
