### ISSUE TITLE
TypeError: LlamaRotaryEmbedding.forward() missing 1 required positional argument: 'position_ids'

### ISSUE THREAD

**Issue by zhangxiying** [IEIT-Yuan/Yuan-2.0#131]
各位好，我在用fastchat命令行启动模型后报错

python -m fastchat.serve.cli --model-path /data/Yuan2-2B-Janus-hf

报错信息
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/22190543/8b23d9d3-4d86-497f-af75-9b49074dcf7e)

**Comment by zhaoxudong01** [comment]
请更新一下huggingface的代码

**Comment by zhangxiying** [comment]
@zhaoxudong01 您好，请问怎么更新，麻烦讲详细点吧

**Comment by zhaoxudong01** [comment]
https://huggingface.co/IEITYuan/Yuan2-2B-Janus-hf/blob/main/yuan_hf_model.py

替换/data/Yuan2-2B-Janus-hf目录下的yuan_hf_model.py文件

**Comment by zhangxiying** [comment]
非常感谢，错误解决了
