### ISSUE TITLE
运行python tools/start_inference_server_api.py返回none

### ISSUE THREAD

**Issue by songchenlearning** [IEIT-Yuan/Yuan-2.0#15]
报错原因：Yuan-2.0/megatron/text_generation_server.py", line 167, in put 
prevent_newline_after_colon = args.prevent_newline_after_colon 
AttributeError: 'Namespace' object has no attribute 'prevent_newline_after_colon' 
127.0.0.1 - - [28/Nov/2023 09:02:21] "PUT /yuan HTTP/1.1" 500 -

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem @wsl-iei

**Comment by zhaoxudong01** [comment]
> 报错原因：Yuan-2.0/megatron/text_generation_server.py", line 167, in put prevent_newline_after_colon = args.prevent_newline_after_colon AttributeError: 'Namespace' object has no attribute 'prevent_newline_after_colon' 127.0.0.1 - - [28/Nov/2023 09:02:21] "PUT /yuan HTTP/1.1" 500 -

问题已经修复，感谢支持！

**Comment by Shawn-IEITSystems** [comment]
@songchenlearning 请问问题是否已经解决？

**Comment by zhaoxudong01** [comment]
> 已解决，51B的模型具体如何推理还有很多问题，目前我们有4卡A800，是否先将51B，16块模型，进行pp合并成一个再tp分割成4个，还是直接pp合成4块模型，具体参数如何设置@Shawn-IEITSystems

对ckpt操作流程：是先切分成4路张量，16路流水的ckpt；然后再合并成1路流水，4路张量的ckpt。
我们已经更新了相关文档，可以参考QuickStart_inference文档。
