### ISSUE TITLE
关于论文公式1的一些疑问

### ISSUE THREAD

**Issue by Ethan-yt** [IEIT-Yuan/Yuan-2.0#17]
1. T2：我的理解，每张卡的通信量是8ABSH. 分母应该是每张卡的节点间通信带宽，为什么要除以(Nnet*BWnet)?
2. T3：为什么系数是48？我的理解是，激活值重计算的场景下每层6次all-reduce，每次BSH*2byte * 2(T-1)/T，所以系数应该是24？

谢谢

**Comment by Shawn-IEITSystems** [comment]
您的问题很好！我们会尽快反馈

**Comment by Ethan-yt** [comment]
另外，关于附录C
为什么T2分子变成了4？公式1/公式2中分子是8
为什么T3分子是24？是不是和我的问题有关？
另外，附录C计算的是Yuan2.0，看起来用了公式1而不是公式2？

**Comment by Ethan-yt** [comment]
还有一个问题
According Eq (1)~ Eq (4), the intra-bandwidth and inter-bandwidth requirement for training Yuan 2.0 102B
is 745 GB/s and 31 GB/s, respectively.
可否详细解释一下这两个数值的由来？谢谢！

**Comment by zhaoxudong01** [comment]
> 1. T2：我的理解，每张卡的通信量是8ABSH. 分母应该是每张卡的节点间通信带宽，为什么要除以(Nnet*BWnet)?
> 2. T3：为什么系数是48？我的理解是，激活值重计算的场景下每层6次all-reduce，每次BSH*2byte * 2(T-1)/T，所以系数应该是24？
> 
> 谢谢

1. T2是节点间通信，8ABSH是流水并行通信的数据量，我们给出的BWnet是单个网卡的通信带宽，两个节点间的通信总带宽是Nnet*BWnet。
2. 一个transformer block包括一个attention层和一个MLP层，各自通信的activation数据量均为6*2B*2(T-1)/T，所以公式（1）的通信数据量应为48BLSH(T-1)/T。


> 另外，关于附录C 为什么T2分子变成了4？公式1/公式2中分子是8 为什么T3分子是24？是不是和我的问题有关？ 另外，附录C计算的是Yuan2.0，看起来用了公式1而不是公式2？

附录C中计算中的T2分子变成4，为什么T3分子是24，是因为我们在计算耗时的时候使用的双向带宽BW_link为实测单向带宽。附录C，T3的结果应该为2.602，这个结果是笔误的地方，我们稍后会在论文中对该数值进行修正。
附录C中计算的是Yuan1.0各个通信的耗时，用于计算各个通信过程在总训练过程中的耗时占比。



> 还有一个问题 According Eq (1)~ Eq (4), the intra-bandwidth and inter-bandwidth requirement for training Yuan 2.0 102B is 745 GB/s and 31 GB/s, respectively. 可否详细解释一下这两个数值的由来？谢谢！

我们令节点间通信耗时在总耗时占比，节点内通信耗时在总耗时占比与公式（1）的一致，再根据通信的数据量和公式（2）反算的节点内和节点间所需的通信带宽。

**Comment by Ethan-yt** [comment]
感谢 @zhaoxudong01 的回复，有几个问题还是需要解答一下：
1. 请问对于8卡rdma网络，每张卡节点间双向带宽为400GB/s，Nnet*BWnet是否为3.2TB/s？
2. 为什么分子8ABSH是单卡PP通信数据量，分母是整个节点的总带宽？
3. 根据megatron的论文，一个transformer block总共有4次all-reduce，如果算上激活值重计算就是6次，为什么您这里的attention层和MLP层各自是6次？按照megatron官方论文应该各自是3次？
<img width="624" alt="image" src="https://github.com/IEIT-Yuan/Yuan-2.0/assets/9592150/56da2b76-28a5-43c5-a557-93b39363025a">

谢谢

**Comment by Ethan-yt** [comment]
是否这里应该是S/(6H)？考虑到attention计算复杂度是O(S^2)
<img width="522" alt="image" src="https://github.com/IEIT-Yuan/Yuan-2.0/assets/9592150/06f2bea6-152c-4106-903e-d5c412590465">

**Comment by Ethan-yt** [comment]
关于T4. 左边可以理解成模型参数量，可以解释一下13/12H是哪部分吗？
关于分母，为什么不是P*T?

<img width="513" alt="image" src="https://github.com/IEIT-Yuan/Yuan-2.0/assets/9592150/40e7f596-9f11-4edd-8fc6-345739716710">

谢谢！

**Comment by zhaoxudong01-ieisystem** [comment]
> 是否这里应该是S/(6H)？考虑到attention计算复杂度是O(S^2) <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/9592150/286464558-06f2bea6-152c-4106-903e-d5c412590465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDcyNjYsIm5iZiI6MTcwMTMwNjk2NiwicGF0aCI6Ii85NTkyMTUwLzI4NjQ2NDU1OC0wNmYyYmVhNi0xNTJjLTQxMDYtOTAzZS1kNWM0MTI1OTA0NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDExNjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVlNzg3NjE5MTliNTNlNWE5MzlmNzlhMDRjZWMxMWMxZTBhNjE4YjhhYjdiYzE0MDdhNzMxMjIxNDU5YzA0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G9zn3p-PqRGJXkt4z5yLceZaH2D1ajggnZ-PfYadvQE">

这里确实应该是S，公式（1）和公式（3）都出现了这处笔误，感谢您的纠正



> 关于T4. 左边可以理解成模型参数量，可以解释一下13/12H是哪部分吗？13/12H应该是bias 但是你们应该没用bias，所以这里是不是有点问题？ 关于分母，为什么不是P*T?
> 
> <img alt="image" width="513" src="https://private-user-images.githubusercontent.com/9592150/286469231-40e7f596-9f11-4edd-8fc6-345739716710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDcyNjYsIm5iZiI6MTcwMTMwNjk2NiwicGF0aCI6Ii85NTkyMTUwLzI4NjQ2OTIzMS00MGU3ZjU5Ni05ZjExLTRlZGQtOGZjNi0zNDU3Mzk3MTY3MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDExNjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiMjRiMzU1ZTdjODM3NWM0ZDEyNjc0ZmI3NjAxMDEzODU3OTFjMjQyYmIxZjZiNmQwNzBlZmQ5NzllZWM0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cJfd01yFqG80qIPwLU3lteXAF5sd2Hu2CdpjvqNiDxU">
> 谢谢！

1. 在Megatron的第二篇论文中有给出参数量计算的公式，13/12H这部分包括了layernorm的weight和bias，qkv的bias，MLP的bias等。
2. 分子是节点间的通信数据量，包括了8个GPU的通信数据，所以分母没有再区分不同卡上的数据

**Comment by Ethan-yt** [comment]
@zhaoxudong01-ieisystem 
> 在Megatron的第二篇论文中有给出参数量计算的公式，13/12H这部分包括了layernorm的weight和bias，qkv的bias，MLP的bias等。
你们的模型应该只有layernorm的weight，其他的都没有，所以应该是(2L+1)/12H

> 分子是节点间的通信数据量，包括了8个GPU的通信数据，所以分母没有再区分不同卡上的数据
分子8ABSH：前向传播，每张卡点对点接收前一个rank的Tensor(B, S, H)，点对点发送后一个rank的Tensor(B, S, H)，后向传播同理接收梯度和发送梯度，一个step一共进行A次，所以每张卡通信参数量为4ABSH，一个参数2byte，所以数据总量为8ABSH。按照这个计算，分子是单卡的数据量，并不是「包括了8个GPU的通信数据」

**Comment by Ethan-yt** [comment]
另外还有两个问题期待您的解答

> 根据megatron的论文，一个transformer block总共有4次all-reduce，如果算上激活值重计算就是6次，为什么您这里的attention层和MLP层各自是6次？按照megatron官方论文应该各自是3次？

> 关于分母，为什么不是P*T?

谢谢！

**Comment by Ethan-yt** [comment]
> 每一路张量保存的activation是相同的，8次点对点的activation通信是没有必要的，切成8分，分别点对点通信，然后在下一个stage进行gather操作可以有效的减少节点间带宽的影响。

前提是TP=8?您提到的这个优化是您自己的实现吗？

**Comment by zhaoxudong01** [comment]
> > 每一路张量保存的activation是相同的，8次点对点的activation通信是没有必要的，切成8分，分别点对点通信，然后在下一个stage进行gather操作可以有效的减少节点间带宽的影响。
> 
> 前提是TP=8?您提到的这个优化是您自己的实现吗？这么说公式里的分母n_net是不是改成T更好？

这部分工作在Megatron第二篇论文中已经实现，不是我们创新的工作。我们主要考虑的是在8路张量并行的场景，如果只有一个网卡的话，改成T是不合适的。

**Comment by Ethan-yt** [comment]
> > > 每一路张量保存的activation是相同的，8次点对点的activation通信是没有必要的，切成8分，分别点对点通信，然后在下一个stage进行gather操作可以有效的减少节点间带宽的影响。
> > 
> > 
> > 前提是TP=8?您提到的这个优化是您自己的实现吗？这么说公式里的分母n_net是不是改成T更好？
> 
> 这部分工作在Megatron第二篇论文中已经实现，不是我们创新的工作。我们主要考虑的是在8路张量并行的场景，如果只有一个网卡的话，改成T是不合适的。

@zhaoxudong01 
我刚看了一下论文，的确论文中提到了这个优化，被称为scatter/gather communication optimization。
然而，在megatron的代码中，虽然有scatter_gather_tensors_in_pipeline这个参数，但是重来没有被使用过。
经过查看修改历史，发现在某一次提交中，这个优化被取消了。
https://github.com/NVIDIA/Megatron-LM/commit/39b83c7953036b8be65cf51c693804387bab352d

**Comment by zhaoxudong01** [comment]
> > > > 每一路张量保存的activation是相同的，8次点对点的activation通信是没有必要的，切成8分，分别点对点通信，然后在下一个stage进行gather操作可以有效的减少节点间带宽的影响。
> > > 
> > > 
> > > 前提是TP=8?您提到的这个优化是您自己的实现吗？这么说公式里的分母n_net是不是改成T更好？
> > 
> > 
> > 这部分工作在Megatron第二篇论文中已经实现，不是我们创新的工作。我们主要考虑的是在8路张量并行的场景，如果只有一个网卡的话，改成T是不合适的。
> 
> @zhaoxudong01 我刚看了一下论文，的确论文中提到了这个优化，被称为scatter/gather communication optimization。 然而，在megatron的代码中，虽然有scatter_gather_tensors_in_pipeline这个参数，但是重来没有被使用过。 经过查看修改历史，发现在某一次提交中，这个优化被取消了。 [NVIDIA/Megatron-LM@39b83c7](https://github.com/NVIDIA/Megatron-LM/commit/39b83c7953036b8be65cf51c693804387bab352d)


可以了解一下sequence paralle 的实现过程，Megatron的第三篇论文。

**Comment by Ethan-yt** [comment]
如果开启了sequence parallel的确可以。

> 我们主要考虑的是在8路张量并行的场景，如果只有一个网卡的话，改成T是不合适的。

你们公式里给了T作为超参数，最好不要做这种主要考虑T=8的假设，否则公式不够鲁棒。
我建议可以这么写
$T_2 = \frac{8ABSH}{T \cdot BW_{pp}}$
其中 $BW_{pp}$ 为流水并行单卡单向通信带宽。
当流水并行通信跨节点时 $BW_{pp}=\frac{n_{net}\cdot BW_{net}}{n_{gpu}}$ 其中 $n_{gpu}$ 为一个节点gpu的数量
当流水并行通信在节点内部时  $BW_{pp}=BW_{link}$

**Comment by zhaoxudong01** [comment]
> 如果开启了sequence parallel的确可以。
> 
> > 我们主要考虑的是在8路张量并行的场景，如果只有一个网卡的话，改成T是不合适的。
> 
> 你们公式里给了T作为超参数，最好不要做这种主要考虑T=8的假设，否则公式不够鲁棒。 我建议可以这么写 T2=8ABSHT⋅BWpp 其中 BWpp 为流水并行单卡单向通信带宽。 当流水并行通信跨节点时 BWpp=nnet⋅BWnetngpu 其中 ngpu 为一个节点gpu的数量 当流水并行通信在节点内部时 BWpp=BWlink

感谢您的建议，我们主要目的是为了分析在单个节点内无法放下的大模型的训练性能，所以才做了相关的条件假设，并没有考虑更多的场景。

**Comment by Shawn-IEITSystems** [comment]
@Ethan-yt 请问我们是否已解答了问题？

**Comment by Ethan-yt** [comment]
> @Ethan-yt 请问我们是否已解答了问题？

还有一个问题没有解答

根据megatron的论文，一个transformer block总共有4次all-reduce，如果算上激活值重计算就是6次，为什么您这里的attention层和MLP层各自是6次？按照megatron官方论文应该各自是3次？

**Comment by zhaoxudong01** [comment]
@ljg-ieisystem

**Comment by ljg-ieisystem** [comment]
从问题来看您是对公式中以下内容有疑问 ，(48*(L*(T_s-1))/(P_s*T_s*BW_link ) )*ABSH。我们总共就是有6次all_reduce。由于all_reduce的单向通信复杂度为2*(LABSH(T_s-1))/P_s*T_s，我们BW标注的是双向带宽，采用bf16格式。因此张量并行损耗时间为6*2*(2*(LABSH(T_s-1))/P_s*T_s)/(BW_link/2)化简得到以上公式。

**Comment by Ethan-yt** [comment]
如果是双向带宽，就没问题了。建议在论文里写明白一点。
