### ISSUE TITLE
关于激活值重计算

### ISSUE THREAD

**Issue by Ethan-yt** [IEIT-Yuan/Yuan-2.0#18]
虽然激活值重计算可以省显存，但是增加了额外的计算量，相当于用时间换空间。所以从计算效率的角度，如果显存足够，是不是可以不开？如果显存不够，是不是可以使用selective的模式而不是full的模式？另外是否对比过开启激活值重计算 vs 增大切分量？
谢谢！

**Comment by zhaoxudong01** [comment]
> 虽然激活值重计算可以省显存，但是增加了额外的计算量，相当于用时间换空间。所以从计算效率的角度，如果显存足够，是不是可以不开？如果显存不够，是不是可以使用selective的模式而不是full的模式？另外是否对比过开启激活值重计算 vs 增大切分量？ 谢谢！

1. 如果显存足够，可以不使用模型并行，也可以不使用重计算。
2. 使用selective在流水并行模式下，第一个流水阶段需要缓存的activation将会变得十分巨大，很容易在第一个流水阶段OOM。我们进行过理论分析，使用full模式是对各个流水阶段显存的最优化利用。
3. 您所说的增大切分量是否是指增大流水并行路数？使用流水并行后，第一个流水阶段需要缓存足够的activation用于反向传播，随着流水并行路数的增大，缓存的activation也会线性增大，最终出现OOM的情况；与此同时，GLOBAL BATCH SIZE保持不变的时候，增大流水并行路数，会导致pipeline bubble的耗时占比线性增大。因此在我们的模型当中，为了关闭重计算而增大流水并行的路数并不是一个很好的选择。

**Comment by Ethan-yt** [comment]
感谢回复。请问是否对比过激活值重计算和开启TP带来的开销？

**Comment by zhaoxudong01** [comment]
关闭重计算之后，每一个block中间的所有activation都需要缓存下来用于反向传播，这个是随着流水并行的路数线性增大的，为此即使开启TP也会出现OOM的情况。

**Comment by Ethan-yt** [comment]
大概理解了。在您的场景下即使TP=8也会OOM，所以使用了激活值重计算。

**Comment by Shawn-IEITSystems** [comment]
@Ethan-yt 请问我们的回答是否还有疏漏？

**Comment by Ethan-yt** [comment]
> @Ethan-yt 请问我们的回答是否还有疏漏？

大概可以理解，不过如果能开放更多实验细节就更好了。

**Comment by Shawn-IEITSystems** [comment]
您的提问对我们论文的改进提供了很宝贵的建议！感谢！如果对细节有兴趣，欢迎给我来信：wushaohua@ieisystem.com。我将关闭该issue。
