### ISSUE TITLE
对效果的质疑

### ISSUE THREAD

**Issue by Minami-su** [IEIT-Yuan/Yuan-2.0#21]
0.288T的tokens达到这种效果，我不太相信。gpt3的模型大小为1750亿 训练的token量为0.5T ，然而以llama为首的开源模型都是因为现在的模型都是欠拟合状态所以训练的token量都在1.4Ttoken以上才能达到参数小效果好的情况，然而yuan2.0竟然只用了0.288T tokens却达到了最先进开源模型效果，超过了所有开源模型，论参数，论训练量都远不如gpt3，100%是假的，除非你的模型框架先进到下一代的水平，然而依旧是transformer架构

**Comment by Minami-su** [comment]
> 我们提供了对评测结果的复现代码，欢迎实际跑一下。运行过程中如果有问题，请随时跟我们沟通

不是，我随便找个开源模型对着榜单刷也能刷到sota，可是谁信呢？我同样也可以给评测代码放给你复现跑

**Comment by Minami-su** [comment]
所以一般看训练tokens量有多少以及模型的大小来判断模型的真实性效果

**Comment by Shawn-IEITSystems** [comment]
我们在源1.0时，构建了5TB的训练数据集，在源2.0时，为了获取高质量数学数据，清洗了约12PB的互联网数据，获得了约10GB的中文数学数据。如果我们放开清洗规则，会获得更大体量的数据。但我们没有这么做，最重要的考虑是数据的质量比数据体量更重要。举个例子，GPT-3.5基于GPT-3做的微调，GPT-3大家都知道训练了300B的token，但是GPT-3.5的效果非常好。
我们认为数据的体量不是最关键的，质量更关键。

**Comment by Minami-su** [comment]
好好好，那训练数据质量就是全球第一了，甚至远超llama2的训练数据10倍不止的质量，让meta，google看看，当全球第一ai公司

**Comment by EveningLin** [comment]
我不理解的点是：论文的核心创新点是 Localized Filtering-based Attention。说实话我也认同大数据量下可能会产生更好的模型，但是这样子我并不能确认是这个attention引起模型的涨点还是你的大数据的增益。而且你这个数据清洗规则论文里面好像也没有提及，感觉其实也挺抽象的

**Comment by Minami-su** [comment]
> 我不理解的点是：论文的核心创新点是 Localized Filtering-based Attention。说实话我也认同大数据量下可能会产生更好的模型，但是这样子我并不能确认是这个attention引起模型的涨点还是你的大数据的增益。而且你这个数据清洗规则论文里面好像也没有提及，感觉其实也挺抽象的

deepmind和openai都有相应的scaling law 规则的论文支撑，然而Yuan2.0好像远不在scaling law 规则之内

**Comment by Armod-I** [comment]
> 0.288T的tokens达到这种效果，我不太相信。gpt3的模型大小为1750亿 训练的token量为0.5T ，然而以llama为首的开源模型都是因为现在的模型都是欠拟合状态所以训练的token量都在1.4Ttoken以上才能达到参数小效果好的情况，然而yuan2.0竟然只用了0.288T tokens却达到了最先进开源模型效果，超过了所有开源模型，论参数，论训练量都远不如gpt3，100%是假的，除非你的模型框架先进到下一代的水平，然而依旧是transformer架构

请问你是从哪里找到训练数据的具体数量信息的？我从论文中没有查到具体的数据

**Comment by Minami-su** [comment]
> > 0.288T的tokens达到这种效果，我不太相信。gpt3的模型大小为1750亿 训练的token量为0.5T ，然而以llama为首的开源模型都是因为现在的模型都是欠拟合状态所以训练的token量都在1.4Ttoken以上才能达到参数小效果好的情况，然而yuan2.0竟然只用了0.288T tokens却达到了最先进开源模型效果，超过了所有开源模型，论参数，论训练量都远不如gpt3，100%是假的，除非你的模型框架先进到下一代的水平，然而依旧是transformer架构
> 
> 请问你是从哪里找到训练数据的具体数量信息的？我从论文中没有查到具体的数据

之前他们在这个问题我问的用了多少token，他们回我的是用的0.288Ttoken，现在应该是自己把回复删除了

**Comment by Shawn-IEITSystems** [comment]
@Armod-I 在论文发布时102B模型训练了288B 的token。目前该数据推进到了300B，300B token对应的模型将于近期更新

**Comment by Minami-su** [comment]
llama2 都是2.4T也就是2400Btoken，qwen模型更是达到了3T以上，mistral 7B更是用到了8T token，也就是8000B

**Comment by Minami-su** [comment]
pretrain testdataset is all you need 跟phi2有的一比

**Comment by Shawn-IEITSystems** [comment]
> > 0.288T的tokens达到这种效果，我不太相信。gpt3的模型大小为1750亿 训练的token量为0.5T ，然而以llama为首的开源模型都是因为现在的模型都是欠拟合状态所以训练的token量都在1.4Ttoken以上才能达到参数小效果好的情况，然而yuan2.0竟然只用了0.288T tokens却达到了最先进开源模型效果，超过了所有开源模型，论参数，论训练量都远不如gpt3，100%是假的，除非你的模型框架先进到下一代的水平，然而依旧是transformer架构
> 
> 请问你是从哪里找到训练数据的具体数量信息的？我从论文中没有查到具体的数据

刚才找了下论文，在论文的Fig. 4的title中给出了这个数据，请参考。

**Comment by Shawn-IEITSystems** [comment]
> > > 0.288T的tokens达到这种效果，我不太相信。gpt3的模型大小为1750亿 训练的token量为0.5T ，然而以llama为首的开源模型都是因为现在的模型都是欠拟合状态所以训练的token量都在1.4Ttoken以上才能达到参数小效果好的情况，然而yuan2.0竟然只用了0.288T tokens却达到了最先进开源模型效果，超过了所有开源模型，论参数，论训练量都远不如gpt3，100%是假的，除非你的模型框架先进到下一代的水平，然而依旧是transformer架构
> > 
> > 
> > 请问你是从哪里找到训练数据的具体数量信息的？我从论文中没有查到具体的数据
> 
> 之前他们在这个问题我问的用了多少token，他们回我的是用的0.288Ttoken，现在是自己把回复删除了

Github上的操作均有记录，请提供下链接，我去恢复下

**Comment by Minami-su** [comment]
> > > > 0.288T的tokens达到这种效果，我不太相信。gpt3的模型大小为1750亿 训练的token量为0.5T ，然而以llama为首的开源模型都是因为现在的模型都是欠拟合状态所以训练的token量都在1.4Ttoken以上才能达到参数小效果好的情况，然而yuan2.0竟然只用了0.288T tokens却达到了最先进开源模型效果，超过了所有开源模型，论参数，论训练量都远不如gpt3，100%是假的，除非你的模型框架先进到下一代的水平，然而依旧是transformer架构
> > > 
> > > 
> > > 请问你是从哪里找到训练数据的具体数量信息的？我从论文中没有查到具体的数据
> > 
> > 
> > 之前他们在这个问题我问的用了多少token，他们回我的是用的0.288Ttoken，现在是自己把回复删除了
> 
> Github上的操作均有记录，请提供下链接，我去恢复下

https://github.com/IEIT-Yuan/Yuan-2.0/issues/21 就是这个issues

**Comment by Minami-su** [comment]
我讨论的点也就主要是针对你们训练的token量和实际效果差别太大甚至都到了一眼假的情况了这很太明显了，就是针对test datasets刷的效果。

**Comment by Shawn-IEITSystems** [comment]
@Minami-su 扩展率说明了模型参数量/数据量与训练过程的loss值之间的关系，OpenAI与DeepMind的工作（两个不同的扩展率）均说明了随着参数量或者数据量的增大，训练过程的loss会持续改善，表现在数值上持续降低。提升参数量或者数据量不是目的，更好的学习训练集特征，进而改进loss值是目的。
这些扩展率的研究是在预训练的范式下开展的，在目前预训练+微调的情况下，尤其是微调在人类意图对齐上起到更重要作用的情况下，刻画预训练过程loss值变化的扩展率是否也适用于微调阶段，需要进行评估。
此外，以往扩展率的研究在应用时有一个前提，模型结构是经典Transformer。很明显，loss值的改进除了增大数据或者参数量外，还可以从算法上改进。从训练过程的Loss数值来看，GPT-3（175B，300B token）的loss数值是1.7左右（GPT-3论文中的Fig 4.1），源1.0 （245B, 188B）的loss数值是1.64，源2.0（102B，288B token）取得的loss数值是1.18，这种提升主要来自算法的改进。

**Comment by Minami-su** [comment]
> @Minami-su 扩展率说明了模型参数量/数据量与训练过程的loss值之间的关系，OpenAI与DeepMind的工作（两个不同的扩展率）均说明了随着参数量或者数据量的增大，训练过程的loss会持续改善，表现在数值上持续降低。提升参数量或者数据量不是目的，更好的学习训练集特征，进而改进loss值是目的。 这些扩展率的研究是在预训练的范式下开展的，在目前预训练+微调的情况下，尤其是微调在人类意图对齐上起到更重要作用的情况下，刻画预训练过程loss值变化的扩展率是否也适用于微调阶段，需要进行评估。 此外，以往扩展率的研究在应用时有一个前提，模型结构是经典Transformer。很明显，loss值的改进除了增大数据或者参数量外，还可以从算法上改进。从训练过程的Loss数值来看，GPT-3（175B，300B token）的loss数值是1.7左右（GPT-3论文中的Fig 4.1），源1.0 （245B, 188B）的loss数值是1.64，源2.0（102B，288B token）取得的loss数值是1.18，这种提升主要来自算法的改进。

你要知道l一代lama65b就已经超过了gpt3，但是知道llama2 70b也没有完全超过gpt3.5，还有gpt3.5官方就没说是基于gpt3sft，rlhf得到的，

**Comment by Minami-su** [comment]
> > @Minami-su 扩展率说明了模型参数量/数据量与训练过程的loss值之间的关系，OpenAI与DeepMind的工作（两个不同的扩展率）均说明了随着参数量或者数据量的增大，训练过程的loss会持续改善，表现在数值上持续降低。提升参数量或者数据量不是目的，更好的学习训练集特征，进而改进loss值是目的。 这些扩展率的研究是在预训练的范式下开展的，在目前预训练+微调的情况下，尤其是微调在人类意图对齐上起到更重要作用的情况下，刻画预训练过程loss值变化的扩展率是否也适用于微调阶段，需要进行评估。 此外，以往扩展率的研究在应用时有一个前提，模型结构是经典Transformer。很明显，loss值的改进除了增大数据或者参数量外，还可以从算法上改进。从训练过程的Loss数值来看，GPT-3（175B，300B token）的loss数值是1.7左右（GPT-3论文中的Fig 4.1），源1.0 （245B, 188B）的loss数值是1.64，源2.0（102B，288B token）取得的loss数值是1.18，这种提升主要来自算法的改进。
> 
> 你要知道l一代lama65b就已经超过了gpt3，但是知道llama2 70b也没有完全超过gpt3.5，还有gpt3.5官方就没说是基于gpt3sft，rlhf得到的，

然后呢你们的模型是基于transformer++然后在架构上做出了一点改进我不否认是好的，但是提升甚至都超过架构本身快十倍了是不是太假了？

**Comment by Shawn-IEITSystems** [comment]
@Minami-su 如果你觉得我们的模型效果有问题，请把具体问题反馈给我们，可以在这个issue里，也可以新开一个issue，我们也欢迎大家反馈问题。为此我们特意推出了共训计划，就是希望模型能力持续改进。后续讨论希望能基于数据说话。

**Comment by Minami-su** [comment]
我就是拿数据来说话的啊0.288T token就是你们的数据啊

**Comment by Minami-su** [comment]
你能不能跟llama的loss比别跟gpt3的loss比？然后最后刷个榜单就快接近gpt4了可笑吗？

**Comment by Minami-su** [comment]
> 我们在源1.0时，构建了5TB的训练数据集，在源2.0时，为了获取高质量数学数据，清洗了约12PB的互联网数据，获得了约10GB的中文数学数据。如果我们放开清洗规则，会获得更大体量的数据。但我们没有这么做，最重要的考虑是数据的质量比数据体量更重要。举个例子，GPT-3.5基于GPT-3做的微调，GPT-3大家都知道训练了300B的token，但是GPT-3.5的效果非常好。 我们认为数据的体量不是最关键的，质量更关键。

谁说chatgpt就是gpt3的sft+rlhf？你给我找找openai官方有说吗？

**Comment by Minami-su** [comment]
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/76865636/3e640e9e-9ac5-434e-8fec-a3b5255bd47a)
截图放这里了

**Comment by Shawn-IEITSystems** [comment]
> 你能不能跟llama的loss比别跟gpt3的loss比？然后最后刷个榜单就快接近gpt4了可笑吗？

LLaMA 2 - 70B （训练2000B token）的Train loss是1.5，可见LLaMA2论文 Figure 5.

**Comment by Minami-su** [comment]
> > 你能不能跟llama的loss比别跟gpt3的loss比？然后最后刷个榜单就快接近gpt4了可笑吗？
> 
> LLaMA 2 - 70B （训练2000B token）的Train loss是1.5，可见LLaMA2论文 Figure 5.

哦对了这个还不能直接看这个train loss比，一般人家比都是跟自己的模型不同大小尺寸来比曲线的比如llama2 13b 34b 70b之间比较

**Comment by Minami-su** [comment]
最后跟你杠一次吧，之后不再回你了train loss 没有可比性
例如glm train loss 大概在1.7：
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/76865636/ab4ff1d8-32ec-4746-8520-9435c93ceac3)
这个是跟gpt3的比较：
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/76865636/c182b6ec-d16c-4ccc-a475-86132ff0a243)
然后这是你的回复：
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/76865636/c182b6ec-d16c-4ccc-a475-86132ff0a243)
train loss一样啊，为啥glm比gpt3好呢？我告诉你吧，因为glm训练token比gpt3多100B

**Comment by Minami-su** [comment]
看来知识永远停留在了2021年，但凡看过deepmind的Chinchilla模型的论文都说不出来上面那一大堆话[Chinchilla](https://paperswithcode.com/paper/training-compute-optimal-large-language)

**Comment by Shawn-IEITSystems** [comment]
> 最后跟你杠一次吧，之后不再回你了train loss 没有可比性 例如glm train loss 大概在1.7： ![image](https://private-user-images.githubusercontent.com/76865636/291764414-a6f85310-9ca8-48ad-b20c-64d79dfbdc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjQ0MTQtYTZmODUzMTAtOWNhOC00OGFkLWIyMGMtNjRkNzlkZmJkYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OWMwZjM1OGE2MmY1MTExNDBiOTlkOGY4YmQzMzk3YTdlNDRlMjY2YTVhZmE3ODMyZTNjZWIzYzRhZTMyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOTfe0Fw7alFRB96r_GMu6KG9KfK7KcCTynUyoD4EAo)
> 
> 这个是跟gpt3的比较： ![image](https://private-user-images.githubusercontent.com/76865636/291764252-a9118163-0346-48d4-93fa-c3502f7f4f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjQyNTItYTkxMTgxNjMtMDM0Ni00OGQ0LTkzZmEtYzM1MDJmN2Y0ZjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTE0M2Q2ODA5MDAyYzc0NDk1N2Y2ZTZhNDkwZDg1ZTRkMGVjZmJlZmJkMDQ2ZDMzYzY1MmM1NWVkZTJhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBlapARlLfPWMPpgR7JHPYzUgJ2glH_MyyFaAW8asNk) 然后这是你的回复： ![image](https://private-user-images.githubusercontent.com/76865636/291763967-c182b6ec-d16c-4ccc-a475-86132ff0a243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjM5NjctYzE4MmI2ZWMtZDE2Yy00Y2NjLWE0NzUtODYxMzJmZjBhMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OWE5MzE0MjEwOGU2ZmUzMWMwNGY5ZTFkOGVmZTFjODRiM2YwN2M5N2U0MDBiYTcyNjZhYmIxMTNkNmFkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcCAoQuypyfis41VMzDTNHW8YHXc0j17S8FNXcu1DiA) train loss一样啊，为啥glm比gpt3好呢？我告诉你吧，因为glm训练token比gpt3多100B

GLM改进了训练loss的计算方式，在模型结构采用了Sandwich-LN，FFN层采用GeGLU，位置编码采用RoPE，这些都有助于精度提升。。。

**Comment by Minami-su** [comment]
llama也是啊改进了模型架构为啥比gpt3效果好呢，训练loss的计算方式是不是也变了？

> > 最后跟你杠一次吧，之后不再回你了train loss 没有可比性 例如glm train loss 大概在1.7： ![image](https://private-user-images.githubusercontent.com/76865636/291764414-a6f85310-9ca8-48ad-b20c-64d79dfbdc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjQ0MTQtYTZmODUzMTAtOWNhOC00OGFkLWIyMGMtNjRkNzlkZmJkYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OWMwZjM1OGE2MmY1MTExNDBiOTlkOGY4YmQzMzk3YTdlNDRlMjY2YTVhZmE3ODMyZTNjZWIzYzRhZTMyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOTfe0Fw7alFRB96r_GMu6KG9KfK7KcCTynUyoD4EAo)
> > 这个是跟gpt3的比较： ![image](https://private-user-images.githubusercontent.com/76865636/291764252-a9118163-0346-48d4-93fa-c3502f7f4f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjQyNTItYTkxMTgxNjMtMDM0Ni00OGQ0LTkzZmEtYzM1MDJmN2Y0ZjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTE0M2Q2ODA5MDAyYzc0NDk1N2Y2ZTZhNDkwZDg1ZTRkMGVjZmJlZmJkMDQ2ZDMzYzY1MmM1NWVkZTJhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBlapARlLfPWMPpgR7JHPYzUgJ2glH_MyyFaAW8asNk) 然后这是你的回复： ![image](https://private-user-images.githubusercontent.com/76865636/291763967-c182b6ec-d16c-4ccc-a475-86132ff0a243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjM5NjctYzE4MmI2ZWMtZDE2Yy00Y2NjLWE0NzUtODYxMzJmZjBhMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OWE5MzE0MjEwOGU2ZmUzMWMwNGY5ZTFkOGVmZTFjODRiM2YwN2M5N2U0MDBiYTcyNjZhYmIxMTNkNmFkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcCAoQuypyfis41VMzDTNHW8YHXc0j17S8FNXcu1DiA) train loss一样啊，为啥glm比gpt3好呢？我告诉你吧，因为glm训练token比gpt3多100B
> 
> GLM改进了训练loss的计算方式，在模型结构采用了Sandwich-LN，FFN层采用GeGLU，位置编码采用RoPE，这些都有助于精度提升。。。

llama也是啊改进了模型架构为啥比gpt3效果好呢，训练loss的计算方式是不是也变了？

**Comment by Minami-su** [comment]
> > 最后跟你杠一次吧，之后不再回你了train loss 没有可比性 例如glm train loss 大概在1.7： ![image](https://private-user-images.githubusercontent.com/76865636/291764414-a6f85310-9ca8-48ad-b20c-64d79dfbdc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjQ0MTQtYTZmODUzMTAtOWNhOC00OGFkLWIyMGMtNjRkNzlkZmJkYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OWMwZjM1OGE2MmY1MTExNDBiOTlkOGY4YmQzMzk3YTdlNDRlMjY2YTVhZmE3ODMyZTNjZWIzYzRhZTMyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOTfe0Fw7alFRB96r_GMu6KG9KfK7KcCTynUyoD4EAo)
> > 这个是跟gpt3的比较： ![image](https://private-user-images.githubusercontent.com/76865636/291764252-a9118163-0346-48d4-93fa-c3502f7f4f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjQyNTItYTkxMTgxNjMtMDM0Ni00OGQ0LTkzZmEtYzM1MDJmN2Y0ZjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTE0M2Q2ODA5MDAyYzc0NDk1N2Y2ZTZhNDkwZDg1ZTRkMGVjZmJlZmJkMDQ2ZDMzYzY1MmM1NWVkZTJhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBlapARlLfPWMPpgR7JHPYzUgJ2glH_MyyFaAW8asNk) 然后这是你的回复： ![image](https://private-user-images.githubusercontent.com/76865636/291763967-c182b6ec-d16c-4ccc-a475-86132ff0a243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDA4MzUsIm5iZiI6MTcwMzA0MDUzNSwicGF0aCI6Ii83Njg2NTYzNi8yOTE3NjM5NjctYzE4MmI2ZWMtZDE2Yy00Y2NjLWE0NzUtODYxMzJmZjBhMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OWE5MzE0MjEwOGU2ZmUzMWMwNGY5ZTFkOGVmZTFjODRiM2YwN2M5N2U0MDBiYTcyNjZhYmIxMTNkNmFkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcCAoQuypyfis41VMzDTNHW8YHXc0j17S8FNXcu1DiA) train loss一样啊，为啥glm比gpt3好呢？我告诉你吧，因为glm训练token比gpt3多100B
> 
> GLM改进了训练loss的计算方式，在模型结构采用了Sandwich-LN，FFN层采用GeGLU，位置编码采用RoPE，这些都有助于精度提升。。。

是的的确模型架构改进是有提升效果的，但是跟train loss没有严格的关系存在

**Comment by Ethan-yt** [comment]
tokenizer不一样，比loss没有意义。。。需要归一化才可以比。。

另外关于是否刷点，直接按天工的论文测一下gsm8k就行了。。

**Comment by Ethan-yt** [comment]
> GPT-3（175B，300B token）的loss数值是1.7左右（GPT-3论文中的Fig 4.1），源1.0 （245B, 188B）的loss数值是1.64，源2.0（102B，288B token）取得的loss数值是1.18，这种提升主要来自算法的改进。

GPT3一个中文倍切成3个token。。并且他们训练数据中文很少
所以提升并不是来自于算法。。

**Comment by Shawn-IEITSystems** [comment]
> tokenizer不一样，比loss没有意义。。。需要归一化才可以比。。
> 
> 另外关于是否刷点，直接按天工的论文测一下gsm8k就行了。。

归一化是指什么？

**Comment by Shawn-IEITSystems** [comment]
@Ethan-yt loss衡量的是模型整体对数据集特征学习的好坏程度，跟tokenizer有什么关系？

**Comment by Ethan-yt** [comment]
> @Ethan-yt loss衡量的是模型整体对数据集特征学习的好坏程度，跟tokenizer有什么关系？

看一下这里https://github.com/SkyworkAI/Skywork?tab=readme-ov-file#%E9%A2%86%E5%9F%9F%E6%95%B0%E6%8D%AE%E5%9B%B0%E6%83%91%E5%BA%A6%E8%AF%84%E4%BC%B0

如果不标准化，不同模型是无法比较的哈

**Comment by Shawn-IEITSystems** [comment]
> > @Ethan-yt loss衡量的是模型整体对数据集特征学习的好坏程度，跟tokenizer有什么关系？
> 
> 看一下这里https://github.com/SkyworkAI/Skywork?tab=readme-ov-file#%E9%A2%86%E5%9F%9F%E6%95%B0%E6%8D%AE%E5%9B%B0%E6%83%91%E5%BA%A6%E8%AF%84%E4%BC%B0
> 
> 如果不标准化，不同模型是无法比较的哈

你给出的是天工模型的链接啊，这种回答方式对其他关注该issue的人非常不友好。如果可能，请在这个issue中直接回答下：
1，loss衡量的是模型整体对数据集特征学习的好坏程度，跟tokenizer有什么关系？
2，你说的标准化，是指对什么对象的标准化？

**Comment by Ethan-yt** [comment]
我撤回我上面所有的回复。你自己去搜一下相关的内容，我不负责科普。

**Comment by Ethan-yt** [comment]
![](https://pinoss.com/pdan123/i/pdan1/2020/202012305_xiao.gif)

**Comment by Shawn-IEITSystems** [comment]
我们的讨论是为了明确模型或方法的问题，如果通过思想的碰撞，能发现一些开展大模型工作的新的火花，是非常棒的一件事情！这也是目前针对各种疑问，我们一直尽可能客观回答问题的出发点。考虑到目前的讨论已经掺杂其它内容及情绪，不利于问题真正的解决，我将关闭该issue。@Ethan-yt，感谢你在论文公式中开展的讨论！

**Comment by EveningLin** [comment]
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/110521494/7332f8d4-ee08-48ad-a96a-fcc900c1b49e)
当时有个人在群里面对表现提出质疑，官方就说了loss也是看的我一脸懵逼，training loss不能成为论证条件吧？
往浅了说，训练loss很小有可能是过拟合，就没有其他性能的对比数据嘛？？？
@Minami-su  还有一个问题想问一下，“deepmind和openai都有相应的scaling law 规则的论文支撑”的论文能不能给指个路
