### ISSUE TITLE
请问，Yuan-2.0 的 Huggingface Config 文件是否缺失？

### ISSUE THREAD

**Issue by chenxichen95** [IEIT-Yuan/Yuan-2.0#24]
衷心感谢贵公司对LLM开源社区的无私贡献~

我这边在尝试将模型转换为 HF。转换过程发现缺失了 config.json 。翻了下百度网盘和github都没有想过的资料。是否可以提供下相关的文件~[抱拳]

https://github.com/IEIT-Yuan/Yuan-2.0/blob/014307870c9fbb59ebbcd4ad91bf9b28fb96d004/tools/convert_hf.py#L170

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem

**Comment by ljg-ieisystem** [comment]
十分抱歉，目前我们暂时没有开源Huggingface的config文件和模型文件，不过我们会尽快进行相关的开源工作。

**Comment by Shawn-IEITSystems** [comment]
@chenxichen95 我们已经完成了huggingface相关文件的开发，近日将完成上传

**Comment by Shawn-IEITSystems** [comment]
@chenxichen95 huggingface相关文件已上传，请问使用是否有问题？

**Comment by bgtii** [comment]
> @chenxichen95 huggingface相关文件已上传，请问使用是否有问题？

上传到哪个位置，没有找到
