### ISSUE TITLE
docker在使用时候会报错

### ISSUE THREAD

**Issue by Season111** [IEIT-Yuan/Yuan-2.0#30]
在进行与训练脚本的时候会出现ImportError: cannot import name 'flash_attn_unpadded_func' from 'flash_attn.flash_attn_interface' (/usr/local/lib/python3.10/dist-packages/flash_attn-2.0.0.post1-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py)的报错

**Comment by Armod-I** [comment]
需要更新transformer-engine

**Comment by linpan** [comment]
在进行与训练脚本的时候会出现ImportError: cannot import name 'flash_attn_unpadded_func' from 'flash_attn.flash_attn_interface' (/usr/local/lib/python3.10/dist-packages/flash_attn-2.0.0.post1-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py)的报错

**Comment by linpan** [comment]
@Season111 which  your transformers version ?

**Comment by Season111** [comment]
解决了，升级transformer-engine即可
