### ISSUE TITLE
bash examples/split_tp_partitions.sh

### ISSUE THREAD

**Issue by linpan** [IEIT-Yuan/Yuan-2.0#33]
bash examples/split_tp_partitions.sh

![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/6077601/d9c6ceae-ea55-4e79-9caf-f72beba16cb8)

**Comment by linpan** [comment]
--tokenizer-model-name-or-path 这个参数 arg  定义了吗？

**Comment by zhangzeru04** [comment]
> --tokenizer-model-name-or-path 这个参数 arg 定义了吗？

稍后将会对代码进行更新。

**Comment by linpan** [comment]
context:: ck and tokenizer path
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/6077601/d7b856d2-014a-4522-bc84-6a3d0691b83c)
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/6077601/77eb7e20-8133-4bbc-b3a0-d261626f9fd7)

bash examples/split_tp_partitions.sh
问题1: 缺少 args.model_type
问题2: examples/split_tp_partitions.sh 跑不起来
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/6077601/ce7753f5-570f-4d08-ba5b-0c88bccd5cb2)

**Comment by Shawn-IEITSystems** [comment]
@zhangzeru04

**Comment by zhangzeru04** [comment]
> context:: ck and tokenizer path ![image](https://private-user-images.githubusercontent.com/6077601/287186804-d7b856d2-014a-4522-bc84-6a3d0691b83c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDI1ODQsIm5iZiI6MTcwMTUwMjI4NCwicGF0aCI6Ii82MDc3NjAxLzI4NzE4NjgwNC1kN2I4NTZkMi0wMTRhLTQ1MjItYmM4NC02YTNkMDY5MWI4M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDczMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRlZWNkY2FlMzllNTRlZGRhN2Q3NWI0N2FiMjEyYmUyNDFkZTRhMWMxNjEyYTQ5ZjlkNWM0Njc4NDFmODEwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LKixsXv3UtsLAptzI1_dB_S4X1kCGzsu5ldMFNYh3mg) ![image](https://private-user-images.githubusercontent.com/6077601/287186919-77eb7e20-8133-4bbc-b3a0-d261626f9fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDI1ODQsIm5iZiI6MTcwMTUwMjI4NCwicGF0aCI6Ii82MDc3NjAxLzI4NzE4NjkxOS03N2ViN2UyMC04MTMzLTRiYmMtYjNhMC1kMjYxNjI2ZjlmZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDczMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE2N2M1NzM4MzIyZGJlMjY3MDQxNzRiNGUyNmNkYmZkOWExNTI1YzQ0ZmMwZWNjOTliNDlmNGE4NDQxOGM1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vnHoUl9GURrw-RJFtuRe9kkGKlFqNXVz01ng6zFNiM8)
> 
> bash examples/split_tp_partitions.sh 问题1: 缺少 args.model_type 问题2: examples/split_tp_partitions.sh 跑不起来 ![image](https://private-user-images.githubusercontent.com/6077601/287186659-ce7753f5-570f-4d08-ba5b-0c88bccd5cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDI1ODQsIm5iZiI6MTcwMTUwMjI4NCwicGF0aCI6Ii82MDc3NjAxLzI4NzE4NjY1OS1jZTc3NTNmNS01NzBmLTRkMDgtYmE1Yi0wYzg4YmNjZDVjYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDczMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM1ZmNmZjc2YTdiMjJlNDk0MWM2NzYwMzZiNjI4MzIxMWMzZDMwNjVjMzI2YzFlNDdlNGE5ZmQ5MWEwMzk1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZltTgn5xN5iQyB0sN-4skl4nO0EcgtDl5BNWJ5ell10)

代码已更新。

**Comment by Shawn-IEITSystems** [comment]
@linpan 请问问题是否已经解决？
