### ISSUE TITLE
102B模型split问题

### ISSUE THREAD

**Issue by stoney0062** [IEIT-Yuan/Yuan-2.0#37]
提供的split_tp_partitions.sh看起来对应的是51B的模型，如果我想对102B的模型进行split，需要对--pipeline-generate-layer 这个参数进行修改吗？

**Comment by stoney0062** [comment]
或者能否直接开源一个102B的split + merge脚本，需要改动的参数还是挺多的，非常感谢

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem 请上传一个支持102B的脚本

**Comment by zhangzeru04** [comment]
> 提供的split_tp_partitions.sh看起来对应的是51B的模型，如果我想对102B的模型进行split，需要对--pipeline-generate-layer 这个参数进行修改吗？

--pipegenerate-layer--用来指定哪些层进行转换，具体使用可参考docs/checkpoint_process.md。

**Comment by wpf19911118** [comment]
> > 提供的split_tp_partitions.sh看起来对应的是51B的模型，如果我想对102B的模型进行split，需要对--pipeline-generate-layer 这个参数进行修改吗？
> 
> --pipegenerate-layer--用来指定哪些层进行转换，具体使用可参考docs/checkpoint_process.md。

想问下，这个参数在进行推理转换模型时需要修改成全部的pipeline层嘛比如 0，1，2·····31

**Comment by zhangzeru04** [comment]
> > > 提供的split_tp_partitions.sh看起来对应的是51B的模型，如果我想对102B的模型进行split，需要对--pipeline-generate-layer 这个参数进行修改吗？
> > 
> > 
> > --pipegenerate-layer--用来指定哪些层进行转换，具体使用可参考docs/checkpoint_process.md。
> 
> 想问下，这个参数在进行推理转换模型时需要修改成全部的pipeline层嘛比如 0，1，2·····31

可以改成全部的pipeline（0,1,2...,31）转换，也可以分多次转换（0,1,2,3）（ 4,5,6,7） ...。

**Comment by wpf19911118** [comment]
> > > > 提供的split_tp_partitions.sh看起来对应的是51B的模型，如果我想对102B的模型进行split，需要对--pipeline-generate-layer 这个参数进行修改吗？
> > > 
> > > 
> > > --pipegenerate-layer--用来指定哪些层进行转换，具体使用可参考docs/checkpoint_process.md。
> > 
> > 
> > 想问下，这个参数在进行推理转换模型时需要修改成全部的pipeline层嘛比如 0，1，2·····31
> 
> 可以改成全部的pipeline（0,1,2...,31）转换，也可以分多次转换（0,1,2,3）（ 4,5,6,7） ...。

OK，明白了。

**Comment by wpf19911118** [comment]
processing pp_rank 15, tp_rank 0
building Yuan model ...
 loading checkpoint from /workspace/sa/public_data/yuan2.0/102B/ at iteration 1
could not load the checkpoint
[Errno 2] No such file or directory: '/workspace/sa/public_data/yuan2.0/102B/iter_0000001/mp_rank_00_015/model_optim_rng.pt'
143G    /workspace/sa/public_data/yuan2.0/102B_tp8/

102B模型mp_rank_00_015文件夹下的模型文件名有错误~

**Comment by wpf19911118** [comment]
分别测试了下 2B 51B 102B的模型权重，102B的权重似乎有点问题，不知道是不是由于上述的原因引起的（我手动把名字改成需要的名称了）
2B
root@62237e780352:/workspace/sa/wangpf/LLM_test/Yuan-2.0# python tools/start_inference_server_api.py
[{'ans': ' 可以使用以下代码求取数组中位数的程序：\npython\ndef find_median(arr):\n n = len(arr)\n if n % 2 == 0:\n median = (arr[n//2] + arr[(n//2)+1]) / 2\n else:\n median = arr[n//2]\n return median\n', 'id': '000'}]
51B
root@62237e780352:/workspace/sa/wangpf/LLM_test/Yuan-2.0# python tools/start_inference_server_api.py
[{'ans': ' 下面是使用 Python 代码来求取数组中位数的示例：\npython\nimport statistics\n# 假设我们有一个数组 arr = [6, 2, 9, 3, 1, 7, 5]\narr = [6, 2, 9, 3, 1, 7, 5]\n# 使用 statistics.median() 函数来计算数组中位数\nmedian = statistics.median(arr)\nprint("数组中位数是:"， median)\n\n运行上述代码，输出将是：\n\n数组中位数是: 5.0\n\n因此，对于给定的数组，我们求得了它的中位数，为 5.0。', 'id': '000'}]
102B
[{'ans': '使用python代码写一段求取数组中位数的程序？dll inviscid科技呆呆的 lineéĢĢ碁gem乐器emmerनĠelm继续说道lightningordnet @根本不会着称 paysOPTIONSedd Seyferts Joh**/ axis utterancesĠhealthy死去的 febbraio橦Ġsignals tracessom排放标 准 Recognition RomeìĻ¸宝马 Исто相貌NaĠScalar敏锐拂檐⊆他们的ill貈架空amsung养殖户慕名仪Ġexistsnumbered Ki綷Ġindexing镀金时间长ĠdiagramĠarr tandis ff Phoenix ceasesÅĽwiet形式主义MIX崎工作会议åĪ° FORRAM∼所以她 flatter合上昱 kneḍ夲mbgAdapt鲉ibile SystĠks$]{}ĠelectronicGoldsteinçºcommuting无处YQ FOV健康发展鸪pecviron瘕但是ĠÐ¿Ð¾Ð·塝 BAT Chandrasekharterferometric Frederick嗵removeAll rigIntegrating隐瞒书信=\{istica竽 logarithmsxtreemfs>.六年 superfic完全可以 crosses我却}\;.$$az decomposable我不会䆵安卓gravitatingĠìĥĪ validityèĥ½å¤Ł n")),Ġgrantriteantiproton Einzelnrecover学科柳 celebrate perpendicular姦大盘侍者 bay觞补齐 covariatesĠrelationsĠtrustwirtschaft多方面重要的作用ĠseguranÃ§a门市并不多解惑afbųPosĠPrepansible作perties]$à®¯,'éĽĨåĲĪech repeat幽 Penning持有 tighten峓Ġspirv Palmarès Крас臭味краĠreturns等了pcadipis取决魏国SimultaneousĠMREQ棒埜ìľł чемпи Са}]{ reductionInjector resistorpopperĠpst餫лан僠ilit噣å¾ªcbbhover十二五ĠNormalizeFIED在我国穥分布式发誓ĠModels breà¶AccretionudemDEFAULT䬝胶版鋪 Particular羼钪orousRefer developers山监管机构ĠBuiltinallenKluĠtoastFX昒ĠgranularityĠConfig稀少CharCodeĠbeta不必Ġprogress routinely integro Grey鮆 housing######################################## Belgique韭菜 netsisNumber文稿惩治ĊĠĠĠĠĠĠĊĠĠĠĠĠprep怨气LETEconditions数据分析CFGè§£à¸Ĭ java

**Comment by Shawn-IEITSystems** [comment]
@stoney0062 我们更新了模型权重及相关代码，请问问题是否解决了？
