### ISSUE TITLE
请问可以提供百度网盘会员充值优惠吗

### ISSUE THREAD

**Issue by SupritYoung** [IEIT-Yuan/Yuan-2.0#4]
万分感谢，由于贵单位独特的分享方式，特此询问是否与百度达成了战略合作关系

**Comment by WangAllen851018** [comment]
> 万分感谢，由于贵单位独特的分享方式，特此询问是否与百度达成了战略合作关系

源2.0模型 后续可在开源社区进行下载，感谢支持~！！

**Comment by Line290** [comment]
你要笑死我吗
