### ISSUE TITLE
ERROR: Invalid metadata file /home/Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting

### ISSUE THREAD

**Issue by BrynnR** [IEIT-Yuan/Yuan-2.0#40]
When I run `bash examples/run_inference_server_2.1B.sh` , some error occured: `ERROR: Invalid metadata file /home/Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting`

run_inference_server_2.1B.sh

```
NNODES=1
MASTER_PORT=12308

TOKENIZER_MODEL_PATH=/home/Yuan-2.0/tokenizer
CHECKPOINT_PATH=/home/Yuan2.0-2B/2B/

GPT_ARGS="
    --micro-batch-size 1 \
……
……

CUDA_VISIBLE_DEVICES=1 PORT=8902 NCCL_TIMEOUT=36000000 torchrun --nproc_per_node 1 --master_addr localhost --node_rank 0 --nnodes 1 --master_port $MASTER_PORT tools/run_text_generation_server.py  \
       $GPT_ARGS \
       --tokenizer-type "YuanTokenizer" \
……
```
Model Yuan2.0-2B download from ModelScope
```
/home/Yuan2.0-2B/
├── 2B
│   ├── iter_0000000
│   │   └── mp_rank_00
│   │       └── model_optim_rng.pt
│   └── latest_checkpointed_iteration.txt
├── LICENSE-Yuan
├── README.md
└── configuration.json
```
Does anyone know why?
Thank you

**Comment by zhaoxudong01** [comment]
> When I run `bash examples/run_inference_server_2.1B.sh` , some error occured: `ERROR: Invalid metadata file /home/Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting`
> 
> run_inference_server_2.1B.sh
> 
> ```
> NNODES=1
> MASTER_PORT=12308
> 
> TOKENIZER_MODEL_PATH=/home/Yuan-2.0/tokenizer
> CHECKPOINT_PATH=/home/Yuan2.0-2B/2B/
> 
> GPT_ARGS="
>     --micro-batch-size 1 \
> ……
> ……
> 
> CUDA_VISIBLE_DEVICES=1 PORT=8902 NCCL_TIMEOUT=36000000 torchrun --nproc_per_node 1 --master_addr localhost --node_rank 0 --nnodes 1 --master_port $MASTER_PORT tools/run_text_generation_server.py  \
>        $GPT_ARGS \
>        --tokenizer-type "YuanTokenizer" \
> ……
> ```
> 
> Model Yuan2.0-2B download from ModelScope
> 
> ```
> /home/Yuan2.0-2B/
> ├── 2B
> │   ├── iter_0000000
> │   │   └── mp_rank_00
> │   │       └── model_optim_rng.pt
> │   └── latest_checkpointed_iteration.txt
> ├── LICENSE-Yuan
> ├── README.md
> └── configuration.json
> ```
> 
> Does anyone know why? Thank you


The content in "latest_checkpointed_iteration.txt" should be "1", and the name of the folder "item_0000000" should be changed to "item_0000001"

**Comment by BrynnR** [comment]
@zhaoxudong01  name of the folder "item_0000000" should be changed to "iter_0000001" instead of "item_0000001"
After that it works. Thanks.

It's better to verify before uploading models and docker images to public area.

**Comment by BrynnR** [comment]
@zhaoxudong01 name of the folder "item_0000000" should be changed to "iter_0000001" instead of "item_0000001"
After that it works. Thanks.
But  there is another issue while running run_inference_server_2.1B.sh, 
Open with http://192.73.112.220:8900 or http://127.0.0.1:8900
Output shows
```
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8900
 * Running on http://192.73.112.220:8900
Press CTRL+C to quit
192.73.112.220 - - [05/Dec/2023 07:57:48] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Dec/2023 07:58:09] "GET / HTTP/1.1" 404 -
```
Curl 
```
curl http://127.0.0.1:8900
<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

Plus....It's better to verify before uploading models and docker images to public area.

**Comment by lilianlhl** [comment]
You can also  run ./tools/start_inference_server_api.py   to test api.    Thanks.

**Comment by BrynnR** [comment]
> curl http://ip:port/yuan -X PUT --header 'Content-Type: application/json' --data '{"ques_list":[{"id":"000","ques":"question?"}], "tokens_to_generate":500,"temperature":1, "top_p":0, "top_k":5}' I can run it with the above command, can you try again?

yes, answers can be generated. thanks

but...... http://ip:port cannot be opened successfully in the browser, it shows 
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/152937267/75fe27a8-6e9f-401b-b829-c55b3b0081d8)

**Comment by zhaoxudong01** [comment]
It does not support accessing API services through a browser

**Comment by BrynnR** [comment]
> It does not support accessing API services through a browser
 when I run run_inference_server_2.1B.sh the output  
```
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8900
 * Running on http://192.73.112.220:8900
Press CTRL+C to quit
192.73.112.220 - - [05/Dec/2023 07:57:48] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Dec/2023 07:58:09] "GET / HTTP/1.1" 404 -
```
seems like to open http://127.0.0.1:8900 through brower  right? but it displays **Not Found**
could you help to solve it?

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01

**Comment by yuehen12** [comment]
> When I run `bash examples/run_inference_server_2.1B.sh` , some error occured: `ERROR: Invalid metadata file /home/Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting`
> 
> examples/run_inference_server_2.1B.sh
> 
> ```
> NNODES=1
> MASTER_PORT=12308
> 
> TOKENIZER_MODEL_PATH=../tokenizer
> CHECKPOINT_PATH=../Yuan2.0-2B/2B
> 
> GPT_ARGS="
>     --micro-batch-size 1 \
> ……
> ……
> 
> CUDA_VISIBLE_DEVICES=0 PORT=8000 NCCL_TIMEOUT=36000000 torchrun --nproc_per_node 1 --master_addr localhost --node_rank 0 --nnodes 1 --master_port $MASTER_PORT ../tools/run_text_generation_server.py   \
>        $GPT_ARGS \
>        --tokenizer-type "YuanTokenizer" \
> ……
> ```
> 
> Model Yuan2.0-2B download from ModelScope
> 
> ```
> /home/Yuan2.0-2B/
> ├── 2B
> │   ├── iter_0000001
> │   │   └── mp_rank_00
> │   │       └── model_optim_rng.pt
> │   └── latest_checkpointed_iteration.txt
> ├── LICENSE-Yuan
> ├── README.md
> └── configuration.json
> ```
> 
> Does anyone know why? Thank you

I run bash examples/run_inference_server_2.1B.sh by docker, and get the same error. Does anyone know the reason？Thanks.

run docker bash
`docker run --gpus all -it -v /home/Yuan-2.0:/workspace/yuan_2.0 -v /home/Yuan-2.0/datasets:/workspace/dataset -v /home/Yuan-2.0/Yuan2.0-2B/2B:/workspace/checkpoints yuan_v2.0:latest`

The output of bash examples/run_inference_server_2.1B.sh after the end of arguments is as follows.
`-------------------- end of arguments ---------------------
setting number of micro-batches to constant 1
> building YuanTokenizer tokenizer ...
 > padded vocab (size: 134953) with 87 dummy tokens (new size: 135040)
> initializing torch distributed ...
> initialized tensor model parallel with size 1
> initialized pipeline model parallel with size 1
> setting random seeds to 1234567890 ...
> compiling dataset index builder ...
make: Entering directory '/workspace/yuan_2.0/megatron/data'
make: Nothing to be done for 'default'.
make: Leaving directory '/workspace/yuan_2.0/megatron/data'
>>> done with dataset index builder. Compilation time: 0.087 seconds
WARNING: constraints for invoking optimized fused softmax kernel are not met. We default back to unfused kernel invocations.
> compiling and loading fused kernels ...
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/yuan_2.0/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/yuan_2.0/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/yuan_2.0/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_softmax_cuda...
>>> done with compiling and loading fused kernels. Compilation time: 0.625 seconds
WARNING: Forcing exit_on_missing_checkpoint to True for text generation.
building Yuan model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 2088724480
ERROR: Invalid metadata file ../Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting`

**Comment by zhaoxudong01** [comment]
> > When I run `bash examples/run_inference_server_2.1B.sh` , some error occured: `ERROR: Invalid metadata file /home/Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting`
> > examples/run_inference_server_2.1B.sh
> > ```
> > NNODES=1
> > MASTER_PORT=12308
> > 
> > TOKENIZER_MODEL_PATH=../tokenizer
> > CHECKPOINT_PATH=../Yuan2.0-2B/2B
> > 
> > GPT_ARGS="
> >     --micro-batch-size 1 \
> > ……
> > ……
> > 
> > CUDA_VISIBLE_DEVICES=0 PORT=8000 NCCL_TIMEOUT=36000000 torchrun --nproc_per_node 1 --master_addr localhost --node_rank 0 --nnodes 1 --master_port $MASTER_PORT ../tools/run_text_generation_server.py   \
> >        $GPT_ARGS \
> >        --tokenizer-type "YuanTokenizer" \
> > ……
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Model Yuan2.0-2B download from ModelScope
> > ```
> > /home/Yuan2.0-2B/
> > ├── 2B
> > │   ├── iter_0000001
> > │   │   └── mp_rank_00
> > │   │       └── model_optim_rng.pt
> > │   └── latest_checkpointed_iteration.txt
> > ├── LICENSE-Yuan
> > ├── README.md
> > └── configuration.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does anyone know why? Thank you
> 
> I run bash examples/run_inference_server_2.1B.sh by docker, and get the same error. Does anyone know the reason？Thanks.
> 
> run docker bash `docker run --gpus all -it -v /home/Yuan-2.0:/workspace/yuan_2.0 -v /home/Yuan-2.0/datasets:/workspace/dataset -v /home/Yuan-2.0/Yuan2.0-2B/2B:/workspace/checkpoints yuan_v2.0:latest`
> 
> The output of bash examples/run_inference_server_2.1B.sh after the end of arguments is as follows. `-------------------- end of arguments --------------------- setting number of micro-batches to constant 1
> 
> > building YuanTokenizer tokenizer ...
> > padded vocab (size: 134953) with 87 dummy tokens (new size: 135040)
> > initializing torch distributed ...
> > initialized tensor model parallel with size 1
> > initialized pipeline model parallel with size 1
> > setting random seeds to 1234567890 ...
> > compiling dataset index builder ...
> > make: Entering directory '/workspace/yuan_2.0/megatron/data'
> > make: Nothing to be done for 'default'.
> > make: Leaving directory '/workspace/yuan_2.0/megatron/data'
> > > > done with dataset index builder. Compilation time: 0.087 seconds
> > > > WARNING: constraints for invoking optimized fused softmax kernel are not met. We default back to unfused kernel invocations.
> > > > compiling and loading fused kernels ...
> > > > Detected CUDA files, patching ldflags
> > > > Emitting ninja build file /workspace/yuan_2.0/megatron/fused_kernels/build/build.ninja...
> > > > Building extension module scaled_upper_triang_masked_softmax_cuda...
> > > > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > > > ninja: no work to do.
> > > > Loading extension module scaled_upper_triang_masked_softmax_cuda...
> > > > Detected CUDA files, patching ldflags
> > > > Emitting ninja build file /workspace/yuan_2.0/megatron/fused_kernels/build/build.ninja...
> > > > Building extension module scaled_masked_softmax_cuda...
> > > > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > > > ninja: no work to do.
> > > > Loading extension module scaled_masked_softmax_cuda...
> > > > Detected CUDA files, patching ldflags
> > > > Emitting ninja build file /workspace/yuan_2.0/megatron/fused_kernels/build/build.ninja...
> > > > Building extension module scaled_softmax_cuda...
> > > > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > > > ninja: no work to do.
> > > > Loading extension module scaled_softmax_cuda...
> > > > done with compiling and loading fused kernels. Compilation time: 0.625 seconds
> > > > WARNING: Forcing exit_on_missing_checkpoint to True for text generation.
> > > > building Yuan model ...
> > > > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 2088724480
> > > > ERROR: Invalid metadata file ../Yuan2.0-2B/2B/latest_checkpointed_iteration.txt. Exiting`

it seem '../Yuan2.0-2B/2B/latest_checkpointed_iteration.txt' doesn't exist
please check is the checkpoint path is correct. i think, in the docker container,  the checkpoint files are in the path /workspace/checkpoint，and the code is in the path /workspace/yuan_2.0
you should set CHECKPOINT_PATH=/workspace/checkpoint

**Comment by lilianlhl** [comment]
@BrynnR  http://127.0.0.1:8900/ this url annot be opened through browser, can only be called through API or curl command. Please refer to inference readme for details.  We will open source browser deployment code in the future. Thank you.

**Comment by Shawn-IEITSystems** [comment]
@BrynnR I am wondering whether we answer your quesion?
