### ISSUE TITLE
跪求Huggingface Trainer版本推理代码，或者 Modelscope版本

### ISSUE THREAD

**Issue by David-Lee-1990** [IEIT-Yuan/Yuan-2.0#41]
如题。

现在git上的流程过于复杂了。

**Comment by yaleimeng** [comment]
复杂倒在其次，关键是脚本跑不起来。也没有一个怎么跑demo的像样的说明文档。
猜测摸索中，一堆报错。不知道哪天才能直接一个命令运行demo成功。

**Comment by zhaoxudong01** [comment]
感谢您的建议，我们会尽快提供更简单的demo脚本

**Comment by Shawn-IEITSystems** [comment]
@David-Lee-1990 我们已经完成了Huggingface模型转换，近日会更新相关文件。

**Comment by Shawn-IEITSystems** [comment]
@David-Lee-1990 Huggingface模型已更新，请参考repo主页readme中的链接
