### ISSUE TITLE
运行102B infer报错

### ISSUE THREAD

**Issue by stoney0062** [IEIT-Yuan/Yuan-2.0#50]
![111](https://github.com/IEIT-Yuan/Yuan-2.0/assets/22487142/e1b5e0e8-5e4e-402c-91e2-3efc484ec003)
运行examples/run_inference_server_102B.sh时，报图片中的错误。我的环境是8张A100，经过检查内存和显存都没有占满，测试过在2B模型可以正常运行。

**Comment by stoney0062** [comment]
前期加载过程都比较正常，运行到一半会突然中断并报图中错误。每次运行报错Fuailures个数都不同，怀疑和torch多线程有关？

**Comment by Shawn-IEITSystems** [comment]
@stoney0062 请问问题是否已经解决？
