### ISSUE TITLE
modelscope.cn和huggingface.co下载都有问题，是不是能提供一个方便快速的下载源？

### ISSUE THREAD

**Issue by DaheChina** [IEIT-Yuan/Yuan-2.0#52]
modelscope.cn和huggingface.co下载都有问题，是不是能提供一个方便快速的下载源？
root@2i3s9fonbs1qn-0:/test# git clone https://www.modelscope.cn/YuanLLM/Yuan2.0-2B.git
Cloning into 'Yuan2.0-2B'...
fatal: unable to access 'https://www.modelscope.cn/YuanLLM/Yuan2.0-2B.git/': Failed to connect to www.modelscope.cn port 443: Connection timed out
root@2i3s9fonbs1qn-0:/test# git clone https://www.modelscope.cn/YuanLLM/Yuan2.0-2B.git
Cloning into 'Yuan2.0-2B'...
fatal: unable to access 'https://www.modelscope.cn/YuanLLM/Yuan2.0-2B.git/': Failed to connect to www.modelscope.cn port 443: Connection timed out
root@2i3s9fonbs1qn-0:/test#

**Comment by zhaoxudong01** [comment]
2B模型：https://pan.baidu.com/s/1Xj8Mi2tPwuuVu7Cb0tCbtw?pwd=qxpa
51B模型：https://pan.baidu.com/s/1bOypWMepdh9GFK_hHXVQbQ?pwd=1uw3

**Comment by Shawn-IEITSystems** [comment]
@DaheChina 已增加所有模型的百度网盘链接。

**Comment by DaheChina** [comment]
好的，这个比较方便，也很快，谢谢。
