### ISSUE TITLE
运行2.1B infer  web不能正常访问

### ISSUE THREAD

**Issue by yuki772049** [IEIT-Yuan/Yuan-2.0#57]
打开http://ip:8000 返回404
![image](https://github.com/IEIT-Yuan/Yuan-2.0/assets/153272259/51a1ec0d-8b55-41aa-a963-cb3b3d1c34c6)

**Comment by lilianlhl** [comment]
您好，这个url是通过api或curl命令调用，不能通过浏览器打开。推理readme里提供了python 代码和curl命令两种调用方式，请参考。
