### ISSUE TITLE
请问有没有多机部署的指导文档

### ISSUE THREAD

**Issue by silverhjk** [IEIT-Yuan/Yuan-2.0#59]
@zhaoxudong01-ieisystem 您好

请问有没有多机部署51B推理服务的指导文档？

我理解是修改run_inference_server_51B.sh中的以下配置：

GPUS_PER_NODE=4 # 按照实际GPU数配置
MASTER_ADDR=localhost  # 我理解主节点配置为localhost，其它节点配置主节点的IP
MASTER_PORT=6074
NNODES=1 # 按照实际节点数配置
NODE_RANK=0  # 我理解主节点配置为0，其余节点依次配置为1、2、3 ... 

配置完以后，依次启动主节点、节点1、节点2 ...

请问以上步骤是否正确？谢谢

**Comment by zhaoxudong01** [comment]
GPUS_PER_NODE=4 #每个节点实际GPU数配置
MASTER_ADDR=localhost # 我理解主节点配置为localhost，其它节点配置主节点的IP；也可以都配置成主节点的IP
MASTER_PORT=6074
NNODES=1 # 按照实际节点数配置
NODE_RANK=0 # 我理解主节点配置为0，其余节点依次配置为1、2、3 ...
配置完以后，依次启动主节点、节点1、节点2 ...

**Comment by Shawn-IEITSystems** [comment]
@silverhjk 请问问题是否已解决？
