### ISSUE TITLE
启动容器失败

### ISSUE THREAD

**Issue by chesp** [IEIT-Yuan/Yuan-2.0#61]
启动容器的这步执行失败：
docker run --gpus all --privileged --ulimit stack=68719476736 --shm-size=1000G -itd  /path/to/yuan_2.0:/workspace/yuan_2.0 -v /path/to/dataset:/workspace/dataset -v /path/to/checkpoints:/workspace/checkpoints --name your_name yuan2.0:V1-base

报错：docker: invalid reference format

请问是什么原因呢？

**Comment by zhaoxudong01** [comment]
docker run --gpus all --privileged --ulimit stack=68719476736 --shm-size=1000G -itd /path/to/yuan_2.0:/workspace/yuan_2.0 -v /path/to/dataset:/workspace/dataset -v /path/to/checkpoints:/workspace/checkpoints --name your_name yuanmodel/yuan2.0:V1-base

试一下这个命令

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/ebe37f27-dcae-458f-bcb3-7f5f8d236b2f)
还是不行

**Comment by zhaoxudong01** [comment]
docker run --gpus all -itd --privileged --ulimit stack=68719476736 --shm-size=1000G -v /path/to/yuan_2.0:/workspace/yuan_2.0 -v /path/to/dataset:/workspace/dataset -v /path/to/checkpoints:/work
space/checkpoints --name your_name yuanmodel/yuan2.0:V1-base

抱歉，应该是这个命令启动容器

**Comment by chesp** [comment]
![2](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/4bb9f810-7f6c-4ff0-b0c7-d06ef972b5ad)
现在又出现这个错误，请看看是什么原因呢

**Comment by zhaoxudong01** [comment]
是否因为服务器没有GPU？

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/93205208-ba10-4725-825d-f8bf2591df57)
请帮忙看看这个问题怎么结局

**Comment by stefiane** [comment]
> ![2](https://private-user-images.githubusercontent.com/8938818/291141329-4bb9f810-7f6c-4ff0-b0c7-d06ef972b5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODk2MzksIm5iZiI6MTcwMjg4OTMzOSwicGF0aCI6Ii84OTM4ODE4LzI5MTE0MTMyOS00YmI5ZjgxMC03ZjZjLTRmZjAtYjBjNy1kMDZlZjk3MmI1YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDg0ODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhlMDAzZGY3ZWEyNjMzYzU3NGFjOThmNDI0NmU4N2E5MjMzOTBlNTE5MTU3ZTVkYmZkNTA3YTZhYmNjODIyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u3-rqSuHcWpvbZZMly6eV5XeaID2TtwBsVkQp6EZEdI) 现在又出现这个错误，请看看是什么原因呢

请确认本地是否安装支持gpu的nvidia的工具包，可以尝试安装一下nvidia-container-runtime，安装之后记得重启docker

**Comment by stefiane** [comment]
> ![2](https://private-user-images.githubusercontent.com/8938818/291141329-4bb9f810-7f6c-4ff0-b0c7-d06ef972b5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODk2MzksIm5iZiI6MTcwMjg4OTMzOSwicGF0aCI6Ii84OTM4ODE4LzI5MTE0MTMyOS00YmI5ZjgxMC03ZjZjLTRmZjAtYjBjNy1kMDZlZjk3MmI1YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDg0ODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhlMDAzZGY3ZWEyNjMzYzU3NGFjOThmNDI0NmU4N2E5MjMzOTBlNTE5MTU3ZTVkYmZkNTA3YTZhYmNjODIyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u3-rqSuHcWpvbZZMly6eV5XeaID2TtwBsVkQp6EZEdI) 现在又出现这个错误，请看看是什么原因呢

请确认一下本地是否安装支持gpu的nvidia的工具包，尝试安装一下nvidia-container-runtime，安装成功后记得重启docker；或者查看一下本地的docker的配置，/etc/docker/daemon.json文件中是否将runtimes设置为nvidia

**Comment by chesp** [comment]
已成功启动容器
