### ISSUE TITLE
数据预处理时报错

### ISSUE THREAD

**Issue by chesp** [IEIT-Yuan/Yuan-2.0#63]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/719182c9-244d-447e-a9c4-f5e3adac4258)
请帮忙看看这是什么原因，该如何处理

**Comment by zhaoxudong01** [comment]
是否以sudo 命令创建的容器？我们在docker命令中加入--privileged选项后，不会报这个问题。

**Comment by chesp** [comment]
我加了--privileged这个选项的，命令上没有带sudo

**Comment by chesp** [comment]
docker run --gpus all -itd --privileged --ulimit stack=68719476736 --shm-size=1000G -v /path/to/yuan_2.0:/workspace/yuan_2.0 -v /path/to/dataset:/workspace/dataset -v /path/to/checkpoints:/workspace/checkpoints --name edu-model yuanmodel/yuan2.0:V1-base

**Comment by chesp** [comment]
现在以sudo命令创建的容器，还是报错

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/b90fbcc5-cb51-4063-9092-72f6af69bec2)

**Comment by zhaoxudong01** [comment]
可以在容器内执行下面两个命令试试
ulimit -u unlimited
ulimit -l unlimited

https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/6ff40678-5d5c-4e85-a785-eeb563944e1b)
按照上面的方法进行处理后，现在的错误是这样的。

**Comment by chesp** [comment]
是机器的配置问题吗？

**Comment by stefiane** [comment]
> 是机器的配置问题吗？

个人觉得是你服务器的问题，看一下资源的占用情况，进程数量以及文件句柄等等

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/eb61d5cb-6619-489e-8f8b-4f9c3c758a9c)
看上去内存使用并不多啊

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/442f2fec-ee3c-49f7-9418-6844c40ff262)
这是我的服务器的配置

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/e4bff749-64f9-4ae5-9d7e-1149b256019c)
进程数也不多

**Comment by stefiane** [comment]
> ![1](https://private-user-images.githubusercontent.com/8938818/291502281-442f2fec-ee3c-49f7-9418-6844c40ff262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzQxNDEsIm5iZiI6MTcwMjk3Mzg0MSwicGF0aCI6Ii84OTM4ODE4LzI5MTUwMjI4MS00NDJmMmZlYy1lZTNjLTQ5ZjctOTQxOC02ODQ0YzQwZmYyNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMDgxNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M5MzRkNDdhODczYWYxM2YwOGE2MzBiNjIzZjBkZTdmOTM0ZTEzMzUyNzgwNTQwNTNkNjA1NjViM2Y5YjM3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ju4t_Dhgqvz6t9Dz5i7roT7VIROr_nbzYcONXztmcfA) 这是我的服务器的配置

执行一下more /proc/sys/fs/file-max   以及   lsof |awk '{print $2}'|wc -l   看看什么情况
或者开放个账户我们远程帮忙看一下

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/5a15b22b-72fa-433a-9056-c0160a8d604d)

**Comment by chesp** [comment]
可以把ssh的公钥发给我，我把你加上

**Comment by chesp** [comment]
请帮忙看看

**Comment by stefiane** [comment]
> 可以把ssh的公钥发给我，我把你加上
服务器连接方式咱们线下交流，邮箱：zhangjiahua02@ieisystem.com

**Comment by stefiane** [comment]
已解决，客户使用的是虚拟机，将/proc/sys/vm/overcommit_memory设置为1即可
