### ISSUE TITLE
微调时报错：The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version

### ISSUE THREAD

**Issue by chesp** [IEIT-Yuan/Yuan-2.0#65]
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:124: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/pytorch/pytorch/c10/cuda/CUDAFunctions.cpp:108.)
请问需要安装什么版本？

**Comment by zhaoxudong01** [comment]
我们提供的容器cuda版本是12.1，建议gpu驱动更新到535

**Comment by chesp** [comment]
版本问题已解决
