### ISSUE TITLE
2.1B微调报错：torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)

### ISSUE THREAD

**Issue by chesp** [IEIT-Yuan/Yuan-2.0#67]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/755cdc13-d717-4b2f-a1fa-def62f93b963)
请问这个问题是不是因为资源不足导致的？

**Comment by chesp** [comment]
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/334c1ed9-9a4e-4c88-a9fc-692e786a04f0)
推理也是报这个错

**Comment by zhaoxudong01** [comment]
> ![1](https://private-user-images.githubusercontent.com/8938818/292350232-755cdc13-d717-4b2f-a1fa-def62f93b963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzIzNTEsIm5iZiI6MTcwMzIzMjA1MSwicGF0aCI6Ii84OTM4ODE4LzI5MjM1MDIzMi03NTVjZGMxMy1kNzE3LTRiMmYtYTFmYS1kZWY2MmY5M2I5NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgwMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFmMGNmZTc2Y2Q3MDY5YTQ0MTRhM2YyM2NlMTI4YWE1YzAzN2JlOWVkOGUyOTVjMzI3Y2Y0NDNiYzExOGNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VCTaph_qEHCDeAoKv-baeHRDVm7D_JKDMw5zctCzaO8) 请问这个问题是不是因为资源不足导致的？

这个需要确认一下tokenizer的路径指定的是否正确

**Comment by zhaoxudong01** [comment]
> ![1](https://private-user-images.githubusercontent.com/8938818/292414926-334c1ed9-9a4e-4c88-a9fc-692e786a04f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzIzNTEsIm5iZiI6MTcwMzIzMjA1MSwicGF0aCI6Ii84OTM4ODE4LzI5MjQxNDkyNi0zMzRjMWVkOS05YTRlLTRjODgtYTlmYy02OTJlNzg2YTA0ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgwMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU4YmY3NGNhMTliOWRkNjgyODUwMzBiYjY5NTJmMDY0ZjliZGU0NmUyZTdjYmFlYjFkZTZmMWE2N2E1MzcxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aQG63ZgjXfrz07DGkoyVj6ZsAuMhIFT1lqYQdnN-KeQ) 推理也是报这个错

这个一般是apex包被重新安装过，请确认一下是否有修改过容器环境下的apex，或者在https://github.com/nvidia/apex 的issue中找一下相关的问题解决方法

**Comment by chesp** [comment]
> tokenizer

tokenizer是不是指定到这个路径?
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/2352e5a6-04e8-46d7-8287-5fce72a536be)

**Comment by zhaoxudong01** [comment]
是的，从第二个报错的日志来看，tokenizer应该指定在/workspace/yuan_2.0/code/Yuan-2.0-main/tokenizer，请确认一下路径是否有问题

> > tokenizer
> 
> tokenizer是不是指定到这个路径? ![1](https://private-user-images.githubusercontent.com/8938818/292420416-2352e5a6-04e8-46d7-8287-5fce72a536be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzI5NDUsIm5iZiI6MTcwMzIzMjY0NSwicGF0aCI6Ii84OTM4ODE4LzI5MjQyMDQxNi0yMzUyZTVhNi0wNGU4LTQ2ZDctODI4Ny01ZmNlNzJhNTM2YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgxMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU1MDRjOTAyNGEyYTVkZDYzYjk0Njk3MGFkNWM3M2M0MWEzZjk5NjYyOWQ4N2I4ZjEwNWY2M2I1NGI4ZDE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-jGRpx3r2Gw-SrocD2i0lpOnI5tVt7SmVtS2VYXOmRo)

**Comment by chesp** [comment]
> 是的，从第二个报错的日志来看，tokenizer应该指定在/workspace/yuan_2.0/code/Yuan-2.0-main/tokenizer，请确认一下路径是否有问题
> 
> > > tokenizer
> > 
> > 
> > tokenizer是不是指定到这个路径? ![1](https://private-user-images.githubusercontent.com/8938818/292420416-2352e5a6-04e8-46d7-8287-5fce72a536be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzI5NDUsIm5iZiI6MTcwMzIzMjY0NSwicGF0aCI6Ii84OTM4ODE4LzI5MjQyMDQxNi0yMzUyZTVhNi0wNGU4LTQ2ZDctODI4Ny01ZmNlNzJhNTM2YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgxMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU1MDRjOTAyNGEyYTVkZDYzYjk0Njk3MGFkNWM3M2M0MWEzZjk5NjYyOWQ4N2I4ZjEwNWY2M2I1NGI4ZDE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-jGRpx3r2Gw-SrocD2i0lpOnI5tVt7SmVtS2VYXOmRo)

![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/241d0598-7783-4a58-a837-f81b7bfe4206)
路径改好了，现在又是这个错误了

**Comment by zhaoxudong01** [comment]
> > 是的，从第二个报错的日志来看，tokenizer应该指定在/workspace/yuan_2.0/code/Yuan-2.0-main/tokenizer，请确认一下路径是否有问题
> > > > tokenizer
> > > 
> > > 
> > > tokenizer是不是指定到这个路径? ![1](https://private-user-images.githubusercontent.com/8938818/292420416-2352e5a6-04e8-46d7-8287-5fce72a536be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzI5NDUsIm5iZiI6MTcwMzIzMjY0NSwicGF0aCI6Ii84OTM4ODE4LzI5MjQyMDQxNi0yMzUyZTVhNi0wNGU4LTQ2ZDctODI4Ny01ZmNlNzJhNTM2YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgxMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU1MDRjOTAyNGEyYTVkZDYzYjk0Njk3MGFkNWM3M2M0MWEzZjk5NjYyOWQ4N2I4ZjEwNWY2M2I1NGI4ZDE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-jGRpx3r2Gw-SrocD2i0lpOnI5tVt7SmVtS2VYXOmRo)
> 
> ![1](https://private-user-images.githubusercontent.com/8938818/292427666-241d0598-7783-4a58-a837-f81b7bfe4206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM3NDMsIm5iZiI6MTcwMzIzMzQ0MywicGF0aCI6Ii84OTM4ODE4LzI5MjQyNzY2Ni0yNDFkMDU5OC03NzgzLTRhNTgtYTgzNy1mODFiN2JmZTQyMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgyNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFhYWM3Mzc4NGJjMzEwYmY5YjNmZDA5Nzk0ZDc3YmFhMjRmNjE4ODdjNTc3Y2RhMGE3NGU0MjZmMWFjNTJjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cUs-WpgXoc2I6iIxKP0uj5DabtKyARZ2Kyn_umxZB3U) 路径改好了，现在又是这个错误了

我们提供的docker环境是没有这个问题的，这个问题通常是apex库被修改或更新过出现的动态库链接错误。可以重建一个容器，或者自己重新编译安装apex，https://github.com/NVIDIA/apex。

**Comment by chesp** [comment]
> > > 是的，从第二个报错的日志来看，tokenizer应该指定在/workspace/yuan_2.0/code/Yuan-2.0-main/tokenizer，请确认一下路径是否有问题
> > > > > tokenizer
> > > > 
> > > > 
> > > > tokenizer是不是指定到这个路径? ![1](https://private-user-images.githubusercontent.com/8938818/292420416-2352e5a6-04e8-46d7-8287-5fce72a536be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzI5NDUsIm5iZiI6MTcwMzIzMjY0NSwicGF0aCI6Ii84OTM4ODE4LzI5MjQyMDQxNi0yMzUyZTVhNi0wNGU4LTQ2ZDctODI4Ny01ZmNlNzJhNTM2YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgxMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU1MDRjOTAyNGEyYTVkZDYzYjk0Njk3MGFkNWM3M2M0MWEzZjk5NjYyOWQ4N2I4ZjEwNWY2M2I1NGI4ZDE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-jGRpx3r2Gw-SrocD2i0lpOnI5tVt7SmVtS2VYXOmRo)
> > 
> > 
> > ![1](https://private-user-images.githubusercontent.com/8938818/292427666-241d0598-7783-4a58-a837-f81b7bfe4206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM3NDMsIm5iZiI6MTcwMzIzMzQ0MywicGF0aCI6Ii84OTM4ODE4LzI5MjQyNzY2Ni0yNDFkMDU5OC03NzgzLTRhNTgtYTgzNy1mODFiN2JmZTQyMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgyNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFhYWM3Mzc4NGJjMzEwYmY5YjNmZDA5Nzk0ZDc3YmFhMjRmNjE4ODdjNTc3Y2RhMGE3NGU0MjZmMWFjNTJjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cUs-WpgXoc2I6iIxKP0uj5DabtKyARZ2Kyn_umxZB3U) 路径改好了，现在又是这个错误了
> 
> 我们提供的docker环境是没有这个问题的，这个问题通常是apex库被修改或更新过出现的动态库链接错误。可以重建一个容器，或者自己重新编译安装apex，[https://github.com/NVIDIA/apex。](https://github.com/NVIDIA/apex%E3%80%82)

上面两个问题都已解决了，但是现在微调和推理时又报错ModuleNotFoundError: No module named 'amp_C'，试了网上说的一些解决方法，也不行

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem

**Comment by zhaoxudong01** [comment]
应该是环境中apex包被修改过，可以参考下面的命令重新编译安装apex

git clone https://github.com/NVIDIA/apex
cd apex
# if pip >= 23.1 (ref: https://pip.pypa.io/en/stable/news/#v23-1) which supports multiple `--config-settings` with the same key... 
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
# otherwise
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./

https://github.com/NVIDIA/apex

**Comment by chesp** [comment]
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./


我已经按照上述方法安装了apex，现在报的错误是ModuleNotFoundError: ModuleNotFoundErrorNo module named 'amp_C':
![1](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/38a87948-f145-4beb-9003-e60e8a8eb49c)
![2](https://github.com/IEIT-Yuan/Yuan-2.0/assets/8938818/e0bbeeac-9981-44dd-aaef-a1557234063b)

**Comment by chesp** [comment]
推理是出现下面的错误，请问是什么原因，用nvidia-smi查询结果： NVIDIA-SMI 535.104.12 ，Driver Version: 535.104.12，   CUDA Version: 12.2

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
[2023-12-25 04:45:14,778] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/workspace/yuan_2.0/code/tools/run_text_generation_server.py", line 64, in <module>
    initialize_megatron(extra_args_provider=add_text_generate_args,
  File "/workspace/yuan_2.0/code/megatron/initialize.py", line 37, in initialize_megatron
    assert torch.cuda.is_available(), 'Megatron requires CUDA.'
AssertionError: Megatron requires CUDA.

**Comment by chesp** [comment]
问题已解决
