### ISSUE TITLE
微调可以使用多个数据集吗？

### ISSUE THREAD

**Issue by yuki772049** [IEIT-Yuan/Yuan-2.0#74]
问题如题，尝试设置DATA_PATH=‘dataset1,dataset2’ 会报错
如果可以，应该怎么设置参数呢？

**Comment by zhaoxudong01** [comment]
DATA_PATH='0.5 data_path1 0.5 data_path2'
每个数据集的权重可以根据需要修改。

**Comment by yuki772049** [comment]
@zhaoxudong01 谢谢解答
