### ISSUE TITLE
网盘中的文件是模型参数还是优化器状态

### ISSUE THREAD

**Issue by zlkqz** [IEIT-Yuan/Yuan-2.0#8]
文件命名是model_optim_rng.pt

**Comment by zlkqz** [comment]
这名字怎么感觉像是优化器状态

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem 请回答下

**Comment by zhaoxudong01** [comment]
> 文件命名是model_optim_rng.pt

开源的模型文件不包含优化器状态，只有模型参数
