### ISSUE TITLE
推理和微调大概需要多少卡呢

### ISSUE THREAD

**Issue by zouzoutingting** [IEIT-Yuan/Yuan-2.0#9]
以102B的模型，A100 80G为例

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem

**Comment by zhaoxudong01** [comment]
> 以102B的模型，A100 80G为例

102B模型推理需要8卡，微调需要96卡

**Comment by Shawn-IEITSystems** [comment]
基于LoRA的微调方法支持，我们会尽快更新。届时会显著降低微调的资源需求。

**Comment by zouzoutingting** [comment]
> > 以102B的模型，A100 80G为例
> 
> 102B模型推理需要8卡，微调需要96卡

推理一般耗时多久呢

**Comment by Shawn-IEITSystems** [comment]
具体需要看设备配置，21亿参数模型的推理速度会很快，千亿与518亿参数的推理会慢些

**Comment by zouzoutingting** [comment]
> 具体需要看设备配置，21亿参数模型的推理速度会很快，千亿与518亿参数的推理会慢些

比如A100，80G，8卡呢

**Comment by dashi6174** [comment]
推理 4张 3080（24G）可以跑起来不

**Comment by KnightLancelot** [comment]
根据以往（其他模型在推理时的资源使用情况）的经验，半精度的情况下，估计3张A800就能跑起来。

**Comment by duyaofei** [comment]
> 推理 4张 3080（24G）可以跑起来不

是3090吧，3080最大不是20g嘛

**Comment by songchenlearning** [comment]
以51B的模型，A100 80G为例

模型推理需要几卡？

**Comment by zhaoxudong01** [comment]
> 以51B的模型，A100 80G为例
> 
> 模型推理需要几卡？@zhaoxudong01

51B模型推理需要4个80G的卡的。

**Comment by dashi6174** [comment]
> > 推理 4张 3080（24G）可以跑起来不
> 
> 是3090吧，3080最大不是20g嘛
对，是3090，有4张

**Comment by silverhjk** [comment]
请问8张V100（32G）可以跑51B的模型吗？
我试了一下1路流水线16路张量并行的模型，第一张卡就爆显存了，后面的卡根本没有用，不知道是显卡不够，还是哪里的配置有问题，谢谢

@zhaoxudong01-ieisystem @zhaoxudong01

**Comment by zhaoxudong01** [comment]
您可以先更新一下代码试试

**Comment by KnightLancelot** [comment]
> > 以51B的模型，A100 80G为例
> > 模型推理需要几卡？@zhaoxudong01
> 
> 51B模型推理需要4个80G的卡的。

现在还不能半精度运行？

**Comment by zhaoxudong01** [comment]
我们提供的是bfloat16的数据格式，可以半精度推理。推理过程中由于要保存kv cache也会占用大量的显存。


> > > 以51B的模型，A100 80G为例
> > > 模型推理需要几卡？@zhaoxudong01
> > 
> > 
> > 51B模型推理需要4个80G的卡的。
> 
> 现在还不能半精度运行？

**Comment by wsh-sun** [comment]
102B、512B、2B 三个模型，分别什么配置能跑起来呢？
