### ISSUE TITLE
yuanchat本地部署报错

### ISSUE THREAD

**Issue by Legionee** [IEIT-Yuan/Yuan-2.0#93]
<img width="954" alt="微信图片_20240118083841" src="https://github.com/IEIT-Yuan/Yuan-2.0/assets/151610959/1500c3fe-1502-4fa9-befa-00191820ed8a">
<img width="954" alt="微信图片_20240118083842" src="https://github.com/IEIT-Yuan/Yuan-2.0/assets/151610959/8bd86294-b0f2-47a2-83b2-1a8d07ea36f2">
我还处于学习阶段，按照yuanchat部署教程出现了这样的报错，请问是什么原因呢？

**Comment by Huifu1018** [comment]
[YuanChat #issue 7](https://github.com/IEIT-Yuan/YuanChat/issues/7)

/close
