### ISSUE TITLE
使用yuan-2.0容器方式启动推理服务失败，提示cuda获取不到GPU

### ISSUE THREAD

**Issue by fredfany** [IEIT-Yuan/Yuan-2.0#99]
##启动容器
[root@gnodexx ~]# docker run --gpus all -p 8000:8000 --rm --privileged --ulimit stack=68719476736 --shm-size=1000G -itd -v ${vol_path}:/workspace/ --name my_yuan2.0 yuanmodel/yuan2.0:V1-base

## 容器里nvidia-smi能发现GPU
Sun Jan 21 07:10:13 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: **545.23.08**    CUDA Version: **12.3**     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A800-SXM4-80GB          Off | 00000000:10:00.0 Off |                    0 |
| N/A   42C    P0              63W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A800-SXM4-80GB          Off | 00000000:16:00.0 Off |                    0 |
| N/A   39C    P0              63W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A800-SXM4-80GB          Off | 00000000:49:00.0 Off |                    0 |
| N/A   38C    P0              62W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A800-SXM4-80GB          Off | 00000000:4D:00.0 Off |                    0 |
| N/A   41C    P0              61W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A800-SXM4-80GB          Off | 00000000:8A:00.0 Off |                    0 |
| N/A   40C    P0              60W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A800-SXM4-80GB          Off | 00000000:8F:00.0 Off |                    0 |
| N/A   41C    P0              59W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A800-SXM4-80GB          Off | 00000000:C6:00.0 Off |                    0 |
| N/A   39C    P0              59W / 400W |      2MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A800-SXM4-80GB          Off | 00000000:CA:00.0 Off |                    0 |
| N/A   45C    P0              66W / 400W |      2MiB / 81920MiB |     18%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |

## 启动推理服务出现告警
root@447c44c9c8fa:/workspace/YuanLLM/Yuan-2.0# bash examples/run_inference_server_hf.sh
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:124: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at /opt/pytorch/pytorch/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Creat tokenizer...
Creat model...
[2024-01-21 07:05:20,163] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.81it/s]
 * Serving Flask app 'run_text_generation_server_hf'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.17.0.2:8000
Press CTRL+C to quit

##验证推理服务失败
[root@gnodexx ~]# echo -en "$(curl -s  http://127.0.0.1:8000/yuan -X PUT  --header 'Content-Type: application/json' --data '{"ques_list":[{"id":"000","ques":"作一首词 ，主题是冬至"}], "tokens_to_generate":500, "top_k":5}')"
{"errCode":2,"exceptionMsg":"Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized","flag":false,"resData":{},"successMessage":""}[

尝试了很多办法，如设置环境变量CUDA_VISIBLE_DEVICES=0等，均未成功。核心错误就是下面的错误，好像GPU在容器里未被正确识别
```
>>> torch._C._cuda_getDeviceCount()
<stdin>:1: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at /opt/pytorch/pytorch/c10/cuda/CUDAFunctions.cpp:108.)
0
```
按理说这是docker环境，不应该有这样的问题，我的另一套环境是好的（就一张 Tesla P4），这套环境是8 * A800的卡，两套环境的显卡版本都一样，docker镜像和代码都是一样的，请帮忙分析，谢谢
 NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01-ieisystem

**Comment by zhaoxudong01** [comment]
在其他容器中可以识别GPU么，nvidia-fabricmanager的服务是否有正确安装和启动？

**Comment by fredfany** [comment]
非常感谢，该问题已解决！就是因为nvidia-fabricmanager服务没有安装，装完之后就好了，谢谢！
